In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import asyncio
import json
from pathlib import Path

import dotenv
import pandas as pd
from tqdm.asyncio import tqdm

dotenv.load_dotenv()


from explain.llm._client import LLMClient, LLMConfig

In [3]:
# Load and process the TSV data
data_path = "/Users/emmanuel.noutahi/Code/hooke-explain/data/curation_v1/perturbations/all_smiles_to_synonym.tsv"
df = pd.read_csv(data_path, sep="\t")

df = df.dropna(subset=["synonyms"])
grouped_df = df.groupby("smiles")["synonyms"].apply(list).reset_index()
grouped_df.columns = ["smiles", "synonym_list"]

In [8]:

# Set up LiteLLM client
config = LLMConfig(
    provider="litellm",
    model="gpt-4o",
)

client = LLMClient(config)

2025-08-12 13:11:45.432 | INFO     | explain.llm._client:__init__:577 - Initialized LiteLLM client with model gpt-4o
2025-08-12 13:11:45.432 | INFO     | explain.llm._client:__init__:694 - Initialized unified LLM client with provider: litellm

In [10]:
def create_molecule_name_prompt(molecules_data):
    """Create a prompt for the LLM to select the top 3 most recognizable names for molecules."""
    prompt = """You are a chemistry expert helping to identify the most recognizable and commonly used names for chemical compounds.

For each molecule below, I will provide:
1. SMILES notation (chemical structure)
2. A list of synonyms/names found in various databases

Your task is to:
1. Select the TOP 3 most well-known, commonly used, or scientifically recognized names from the PROVIDED synonym list
2. Prioritize names in this order:
   - Common drug names (if it's a pharmaceutical compound)
   - Well-known scientific names
   - Standard chemical names (IUPAC preferred)
   - Research compound codes (if widely recognized)
3. Provide a brief reason for each selection
4. If you don't recognize the compound or none of the names seem well-known, return null for that molecule
5. IMPORTANT: Only select names that exist in the provided synonym list

Return ONLY a valid JSON array (no markdown, no code blocks) where each object has:
{
  "smiles": "the SMILES string",
  "top_names": ["name1", "name2", "name3"] or null,
  "reasons": ["reason1", "reason2", "reason3"] or null
}

Here are the molecules to analyze:

"""

    for i, mol_data in enumerate(molecules_data, 1):
        prompt += f"\n{i}. SMILES: {mol_data['smiles']}\n"
        prompt += f"   Synonyms: {mol_data['synonyms']}\n"

    prompt += "\nReturn ONLY the JSON array (no markdown formatting):"
    return prompt


def parse_llm_response(response_content):
    """Parse LLM response, handling markdown code blocks and other formatting."""
    try:
        # Remove markdown code blocks if present
        content = response_content.strip()
        if content.startswith("```json"):
            content = content[7:]  # Remove ```json
        elif content.startswith("```"):
            content = content[3:]  # Remove ```

        if content.endswith("```"):
            content = content[:-3]  # Remove closing ```

        content = content.strip()

        # Parse JSON
        return json.loads(content)

    except json.JSONDecodeError as e:
        print(f"JSON parsing failed: {e}")
        print(f"Content to parse: {content[:200]}...")
        return None
    except Exception as e:
        print(f"Unexpected error parsing response: {e}")
        return None


async def process_molecules_batch(client, molecules_batch, semaphore, batch_id, checkpoint_dir):
    """Process a batch of molecules through the LLM and save immediately."""
    batch_file = Path(checkpoint_dir) / f"batch_{batch_id:04d}.json"

    # Check if this batch was already processed
    if batch_file.exists():
        print(f"Batch {batch_id} already exists, skipping...")
        with open(batch_file) as f:
            return json.load(f)

    async with semaphore:
        try:
            # Prepare batch data
            batch_data = []
            for _, row in molecules_batch.iterrows():
                batch_data.append({"smiles": row["smiles"], "synonyms": row["synonym_list"]})

            # Create prompt and call LLM
            prompt = create_molecule_name_prompt(batch_data)
            messages = [{"role": "user", "content": prompt}]
            response = await client.agenerate(messages)

            # Parse response with improved parser
            results = parse_llm_response(response.content)

            if results is None:
                print(f"Failed to parse LLM response for batch {batch_id}, using empty results")
                # Return empty results for this batch
                results = [
                    {"smiles": row["smiles"], "top_names": None, "reasons": None}
                    for _, row in molecules_batch.iterrows()
                ]

            # Save batch result immediately
            with open(batch_file, "w") as f:
                json.dump(results, f, indent=2)
            print(f"Saved batch {batch_id} to {batch_file}")

            return results

        except Exception as e:
            print(f"Batch {batch_id} processing failed: {e}")
            # Create empty results and save them
            results = [
                {"smiles": row["smiles"], "top_names": None, "reasons": None} for _, row in molecules_batch.iterrows()
            ]

            with open(batch_file, "w") as f:
                json.dump(results, f, indent=2)
            print(f"Saved failed batch {batch_id} with empty results")

            return results


def create_batches(df, batch_size=5):
    """Create batches of molecules for processing."""
    batches = []
    for i in range(0, len(df), batch_size):
        batches.append(df.iloc[i : i + batch_size])
    return batches


def load_all_batch_results(checkpoint_dir):
    """Load all completed batch results from individual files."""
    checkpoint_path = Path(checkpoint_dir)
    if not checkpoint_path.exists():
        return []

    all_results = []
    batch_files = sorted(checkpoint_path.glob("batch_*.json"))

    for batch_file in batch_files:
        try:
            with open(batch_file) as f:
                batch_results = json.load(f)
                all_results.extend(batch_results)
        except Exception as e:
            print(f"Error loading {batch_file}: {e}")

    return all_results


async def process_with_checkpoint(
    client,
    df,
    batch_size=10,
    max_batches=None,
    max_concurrent=3,
    checkpoint_dir="../../data/curation_v1/perturbations/cmpds_names/",
):
    """Process molecules with batch-level checkpointing."""

    # Setup
    checkpoint_path = Path(checkpoint_dir)
    checkpoint_path.mkdir(parents=True, exist_ok=True)

    # Load existing results from individual batch files
    existing_results = load_all_batch_results(checkpoint_dir)
    processed_smiles = {r["smiles"] for r in existing_results}

    if existing_results:
        print(
            f"Found {len(existing_results)} existing results from {len(list(checkpoint_path.glob('batch_*.json')))} batch files"
        )

    # Filter out already processed molecules
    remaining_df = df[~df["smiles"].isin(processed_smiles)].reset_index(drop=True)

    if len(remaining_df) == 0:
        print("All molecules already processed!")
        return pd.DataFrame(existing_results)

    # Create batches from remaining molecules
    batches = create_batches(remaining_df, batch_size)
    if max_batches:
        batches = batches[:max_batches]

    print(f"Processing {len(batches)} new batches ({len(remaining_df)} molecules)")

    # Calculate starting batch ID (based on existing batch files)
    existing_batch_files = list(checkpoint_path.glob("batch_*.json"))
    if existing_batch_files:
        start_batch_id = len(existing_batch_files)
    else:
        start_batch_id = 0

    # Process batches with individual saving
    semaphore = asyncio.Semaphore(max_concurrent)
    tasks = [
        process_molecules_batch(client, batch, semaphore, start_batch_id + i, checkpoint_dir)
        for i, batch in enumerate(batches)
    ]

    # Run with progress bar
    print("Processing batches (each batch saved immediately)...")
    batch_results = await tqdm.gather(*tasks, desc="Processing")

    # Load all results (existing + new)
    all_results = load_all_batch_results(checkpoint_dir)

    # Also save consolidated results
    consolidated_file = checkpoint_path / "all_results.json"
    with open(consolidated_file, "w") as f:
        json.dump(all_results, f, indent=2)

    print(f"Processed {len(batch_results)} new batches")
    print(f"Total results: {len(all_results)} molecules")
    print(f"Consolidated results saved to: {consolidated_file}")

    return pd.DataFrame(all_results)


def create_final_dataframe(results_df):
    """Create the final dataframe with separate columns for each top name and reason."""
    final_data = []

    for _, row in results_df.iterrows():
        result_row = {
            "smiles": row["smiles"],
            "top_name_1": None,
            "top_name_2": None,
            "top_name_3": None,
            "reason_1": None,
            "reason_2": None,
            "reason_3": None,
        }

        if row.get("top_names") and isinstance(row["top_names"], list):
            for i, name in enumerate(row["top_names"][:3]):
                result_row[f"top_name_{i + 1}"] = name

        if row.get("reasons") and isinstance(row["reasons"], list):
            for i, reason in enumerate(row["reasons"][:3]):
                result_row[f"reason_{i + 1}"] = reason

        final_data.append(result_row)

    return pd.DataFrame(final_data)


def check_progress(checkpoint_dir="../../data/curation_v1/perturbations/cmpds_names/"):
    """Check current progress."""
    checkpoint_path = Path(checkpoint_dir)
    if not checkpoint_path.exists():
        print("No checkpoint directory found")
        return 0, 0

    # Count batch files
    batch_files = list(checkpoint_path.glob("batch_*.json"))
    print(f"Found {len(batch_files)} completed batches")

    # Load all results
    all_results = load_all_batch_results(checkpoint_dir)
    successful = sum(1 for r in all_results if r.get("top_names"))

    print(f"Total molecules: {len(all_results)}")
    print(f"Successful: {successful}")

    return len(all_results), successful


def clear_results(checkpoint_dir="../../data/curation_v1/perturbations/cmpds_names/"):
    """Clear saved results to start fresh."""
    checkpoint_path = Path(checkpoint_dir)
    if checkpoint_path.exists():
        import shutil

        shutil.rmtree(checkpoint_path)
        print(f"Cleared all results from {checkpoint_path}")
    else:
        print("No results to clear")


print("All functions loaded with per-batch saving!")

All functions loaded with per-batch saving!

In [12]:
results_df = await process_with_checkpoint(
    client,
    grouped_df,
    batch_size=10,
    max_batches=None,  # Set to None for full dataset
    max_concurrent=10,
)
final_df = create_final_dataframe(results_df)

Processing 947 new batches (9463 molecules)
Processing batches (each batch saved immediately)...

Processing:   0%|          | 0/947 [00:00<?, ?it/s]

Processing:   0%|          | 1/947 [00:06<1:36:00,  6.09s/it]

Saved batch 86 to ../../data/curation_v1/perturbations/cmpds_names/batch_0086.json

Processing:   0%|          | 2/947 [00:06<41:56,  2.66s/it]

Saved batch 243 to ../../data/curation_v1/perturbations/cmpds_names/batch_0243.json

Processing:   0%|          | 3/947 [00:07<31:16,  1.99s/it]

Saved batch 632 to ../../data/curation_v1/perturbations/cmpds_names/batch_0632.json

Processing:   0%|          | 4/947 [00:08<21:51,  1.39s/it]

Saved batch 866 to ../../data/curation_v1/perturbations/cmpds_names/batch_0866.json

Processing:   1%|          | 5/947 [00:08<19:10,  1.22s/it]

Saved batch 476 to ../../data/curation_v1/perturbations/cmpds_names/batch_0476.json

Processing:   1%|          | 6/947 [00:11<28:41,  1.83s/it]

Saved batch 87 to ../../data/curation_v1/perturbations/cmpds_names/batch_0087.json

Processing:   1%|          | 7/947 [00:13<25:58,  1.66s/it]

Saved batch 12 to ../../data/curation_v1/perturbations/cmpds_names/batch_0012.json

Processing:   1%|          | 8/947 [00:14<22:41,  1.45s/it]

Saved batch 242 to ../../data/curation_v1/perturbations/cmpds_names/batch_0242.json

Processing:   1%|          | 10/947 [00:16<18:23,  1.18s/it]

Saved batch 13 to ../../data/curation_v1/perturbations/cmpds_names/batch_0013.json
Saved batch 788 to ../../data/curation_v1/perturbations/cmpds_names/batch_0788.json

Processing:   1%|          | 11/947 [00:18<21:06,  1.35s/it]

Saved batch 477 to ../../data/curation_v1/perturbations/cmpds_names/batch_0477.json

Processing:   1%|▏         | 12/947 [00:18<17:33,  1.13s/it]

Saved batch 789 to ../../data/curation_v1/perturbations/cmpds_names/batch_0789.json

Processing:   1%|▏         | 13/947 [00:19<14:40,  1.06it/s]

Saved batch 244 to ../../data/curation_v1/perturbations/cmpds_names/batch_0244.json

Processing:   1%|▏         | 14/947 [00:21<18:23,  1.18s/it]

Saved batch 867 to ../../data/curation_v1/perturbations/cmpds_names/batch_0867.json

Processing:   2%|▏         | 15/947 [00:23<23:28,  1.51s/it]

Saved batch 633 to ../../data/curation_v1/perturbations/cmpds_names/batch_0633.json

Processing:   2%|▏         | 16/947 [00:23<17:21,  1.12s/it]

Saved batch 88 to ../../data/curation_v1/perturbations/cmpds_names/batch_0088.json

Processing:   2%|▏         | 17/947 [00:25<22:09,  1.43s/it]

Saved batch 245 to ../../data/curation_v1/perturbations/cmpds_names/batch_0245.json

Processing:   2%|▏         | 18/947 [00:26<21:23,  1.38s/it]

Saved batch 478 to ../../data/curation_v1/perturbations/cmpds_names/batch_0478.json
Saved batch 89 to ../../data/curation_v1/perturbations/cmpds_names/batch_0089.json

Processing:   2%|▏         | 20/947 [00:27<13:08,  1.18it/s]

Saved batch 11 to ../../data/curation_v1/perturbations/cmpds_names/batch_0011.json

Processing:   2%|▏         | 21/947 [00:28<13:56,  1.11it/s]

Saved batch 868 to ../../data/curation_v1/perturbations/cmpds_names/batch_0868.json

Processing:   2%|▏         | 22/947 [00:29<13:48,  1.12it/s]

Saved batch 14 to ../../data/curation_v1/perturbations/cmpds_names/batch_0014.json

Processing:   2%|▏         | 23/947 [00:30<15:49,  1.03s/it]

Saved batch 790 to ../../data/curation_v1/perturbations/cmpds_names/batch_0790.json

Processing:   3%|▎         | 24/947 [00:33<21:12,  1.38s/it]

Saved batch 634 to ../../data/curation_v1/perturbations/cmpds_names/batch_0634.json

Processing:   3%|▎         | 25/947 [00:33<16:57,  1.10s/it]

Saved batch 479 to ../../data/curation_v1/perturbations/cmpds_names/batch_0479.json

Processing:   3%|▎         | 26/947 [00:34<18:44,  1.22s/it]

Saved batch 246 to ../../data/curation_v1/perturbations/cmpds_names/batch_0246.json

Processing:   3%|▎         | 27/947 [00:35<14:56,  1.03it/s]

Saved batch 869 to ../../data/curation_v1/perturbations/cmpds_names/batch_0869.json

Processing:   3%|▎         | 28/947 [00:35<13:16,  1.15it/s]

Saved batch 635 to ../../data/curation_v1/perturbations/cmpds_names/batch_0635.json

Processing:   3%|▎         | 29/947 [00:36<12:46,  1.20it/s]

Saved batch 10 to ../../data/curation_v1/perturbations/cmpds_names/batch_0010.json
Saved batch 791 to ../../data/curation_v1/perturbations/cmpds_names/batch_0791.json

Processing:   3%|▎         | 31/947 [00:40<21:41,  1.42s/it]

Saved batch 480 to ../../data/curation_v1/perturbations/cmpds_names/batch_0480.json

Processing:   3%|▎         | 32/947 [00:42<23:39,  1.55s/it]

Saved batch 247 to ../../data/curation_v1/perturbations/cmpds_names/batch_0247.json

Processing:   3%|▎         | 33/947 [00:51<52:57,  3.48s/it]

Saved batch 636 to ../../data/curation_v1/perturbations/cmpds_names/batch_0636.json

Processing:   4%|▎         | 34/947 [00:56<57:08,  3.76s/it]

Saved batch 870 to ../../data/curation_v1/perturbations/cmpds_names/batch_0870.json

Processing:   4%|▎         | 35/947 [01:04<1:16:32,  5.04s/it]

Saved batch 792 to ../../data/curation_v1/perturbations/cmpds_names/batch_0792.json

Processing:   4%|▍         | 36/947 [01:05<1:00:00,  3.95s/it]

Saved batch 90 to ../../data/curation_v1/perturbations/cmpds_names/batch_0090.json

Processing:   4%|▍         | 37/947 [01:12<1:12:44,  4.80s/it]

Saved batch 91 to ../../data/curation_v1/perturbations/cmpds_names/batch_0091.json

Processing:   4%|▍         | 38/947 [01:24<1:41:39,  6.71s/it]

Saved batch 637 to ../../data/curation_v1/perturbations/cmpds_names/batch_0637.json

Processing:   4%|▍         | 39/947 [01:26<1:24:18,  5.57s/it]

Saved batch 481 to ../../data/curation_v1/perturbations/cmpds_names/batch_0481.json

Processing:   4%|▍         | 40/947 [01:28<1:05:38,  4.34s/it]

Saved batch 19 to ../../data/curation_v1/perturbations/cmpds_names/batch_0019.json

Processing:   4%|▍         | 41/947 [01:31<58:33,  3.88s/it]

Saved batch 871 to ../../data/curation_v1/perturbations/cmpds_names/batch_0871.json

Processing:   4%|▍         | 42/947 [01:31<42:22,  2.81s/it]

Saved batch 18 to ../../data/curation_v1/perturbations/cmpds_names/batch_0018.json

Processing:   5%|▍         | 43/947 [01:36<50:36,  3.36s/it]

Saved batch 638 to ../../data/curation_v1/perturbations/cmpds_names/batch_0638.json

Processing:   5%|▍         | 44/947 [01:36<36:51,  2.45s/it]

Saved batch 17 to ../../data/curation_v1/perturbations/cmpds_names/batch_0017.json

Processing:   5%|▍         | 45/947 [01:37<31:14,  2.08s/it]

Saved batch 92 to ../../data/curation_v1/perturbations/cmpds_names/batch_0092.json

Processing:   5%|▍         | 46/947 [01:39<30:51,  2.05s/it]

Saved batch 93 to ../../data/curation_v1/perturbations/cmpds_names/batch_0093.json

Processing:   5%|▍         | 47/947 [01:40<24:39,  1.64s/it]

Saved batch 793 to ../../data/curation_v1/perturbations/cmpds_names/batch_0793.json

Processing:   5%|▌         | 48/947 [01:42<28:10,  1.88s/it]

Saved batch 482 to ../../data/curation_v1/perturbations/cmpds_names/batch_0482.json

Processing:   5%|▌         | 49/947 [01:43<22:46,  1.52s/it]

Saved batch 248 to ../../data/curation_v1/perturbations/cmpds_names/batch_0248.json
Saved batch 872 to ../../data/curation_v1/perturbations/cmpds_names/batch_0872.json

Processing:   5%|▌         | 51/947 [01:44<16:07,  1.08s/it]

Saved batch 249 to ../../data/curation_v1/perturbations/cmpds_names/batch_0249.json

Processing:   5%|▌         | 52/947 [01:45<16:49,  1.13s/it]

Saved batch 16 to ../../data/curation_v1/perturbations/cmpds_names/batch_0016.json

Processing:   6%|▌         | 53/947 [01:46<15:25,  1.03s/it]

Saved batch 639 to ../../data/curation_v1/perturbations/cmpds_names/batch_0639.json

Processing:   6%|▌         | 54/947 [01:50<25:25,  1.71s/it]

Saved batch 794 to ../../data/curation_v1/perturbations/cmpds_names/batch_0794.json

Processing:   6%|▌         | 55/947 [01:51<22:10,  1.49s/it]

Saved batch 795 to ../../data/curation_v1/perturbations/cmpds_names/batch_0795.json

Processing:   6%|▌         | 56/947 [01:51<17:24,  1.17s/it]

Saved batch 483 to ../../data/curation_v1/perturbations/cmpds_names/batch_0483.json

Processing:   6%|▌         | 57/947 [01:52<18:04,  1.22s/it]

Saved batch 873 to ../../data/curation_v1/perturbations/cmpds_names/batch_0873.json
Saved batch 250 to ../../data/curation_v1/perturbations/cmpds_names/batch_0250.json

Processing:   6%|▌         | 59/947 [01:53<11:09,  1.33it/s]

Saved batch 796 to ../../data/curation_v1/perturbations/cmpds_names/batch_0796.json

Processing:   6%|▋         | 60/947 [01:54<11:54,  1.24it/s]

Saved batch 94 to ../../data/curation_v1/perturbations/cmpds_names/batch_0094.json

Processing:   6%|▋         | 61/947 [01:54<10:03,  1.47it/s]

Saved batch 640 to ../../data/curation_v1/perturbations/cmpds_names/batch_0640.json

Processing:   7%|▋         | 62/947 [01:56<14:54,  1.01s/it]

Saved batch 15 to ../../data/curation_v1/perturbations/cmpds_names/batch_0015.json

Processing:   7%|▋         | 63/947 [01:57<17:23,  1.18s/it]

Saved batch 797 to ../../data/curation_v1/perturbations/cmpds_names/batch_0797.json

Processing:   7%|▋         | 64/947 [01:58<14:15,  1.03it/s]

Saved batch 251 to ../../data/curation_v1/perturbations/cmpds_names/batch_0251.json

Processing:   7%|▋         | 65/947 [01:58<11:05,  1.32it/s]

Saved batch 484 to ../../data/curation_v1/perturbations/cmpds_names/batch_0484.json

Processing:   7%|▋         | 66/947 [01:58<08:54,  1.65it/s]

Saved batch 874 to ../../data/curation_v1/perturbations/cmpds_names/batch_0874.json

Processing:   7%|▋         | 67/947 [02:00<14:42,  1.00s/it]

Saved batch 95 to ../../data/curation_v1/perturbations/cmpds_names/batch_0095.json

Processing:   7%|▋         | 68/947 [02:01<11:36,  1.26it/s]

Saved batch 641 to ../../data/curation_v1/perturbations/cmpds_names/batch_0641.json

Processing:   7%|▋         | 69/947 [02:01<09:46,  1.50it/s]

Saved batch 31 to ../../data/curation_v1/perturbations/cmpds_names/batch_0031.json
Saved batch 96 to ../../data/curation_v1/perturbations/cmpds_names/batch_0096.json

Processing:   7%|▋         | 71/947 [02:01<06:11,  2.36it/s]

Saved batch 485 to ../../data/curation_v1/perturbations/cmpds_names/batch_0485.json

Processing:   8%|▊         | 72/947 [02:04<13:59,  1.04it/s]

Saved batch 798 to ../../data/curation_v1/perturbations/cmpds_names/batch_0798.json

Processing:   8%|▊         | 73/947 [02:05<16:29,  1.13s/it]

Saved batch 252 to ../../data/curation_v1/perturbations/cmpds_names/batch_0252.json

Processing:   8%|▊         | 74/947 [02:06<13:10,  1.10it/s]

Saved batch 642 to ../../data/curation_v1/perturbations/cmpds_names/batch_0642.json
Saved batch 875 to ../../data/curation_v1/perturbations/cmpds_names/batch_0875.json

Processing:   8%|▊         | 77/947 [02:07<09:40,  1.50it/s]

Saved batch 876 to ../../data/curation_v1/perturbations/cmpds_names/batch_0876.json
Saved batch 97 to ../../data/curation_v1/perturbations/cmpds_names/batch_0097.json

Processing:   8%|▊         | 78/947 [02:09<11:20,  1.28it/s]

Saved batch 30 to ../../data/curation_v1/perturbations/cmpds_names/batch_0030.json

Processing:   8%|▊         | 79/947 [02:09<11:52,  1.22it/s]

Saved batch 253 to ../../data/curation_v1/perturbations/cmpds_names/batch_0253.json

Processing:   8%|▊         | 80/947 [02:10<09:25,  1.53it/s]

Saved batch 799 to ../../data/curation_v1/perturbations/cmpds_names/batch_0799.json

Processing:   9%|▊         | 81/947 [02:10<08:26,  1.71it/s]

Saved batch 486 to ../../data/curation_v1/perturbations/cmpds_names/batch_0486.json

Processing:   9%|▊         | 82/947 [02:11<09:31,  1.51it/s]

Saved batch 487 to ../../data/curation_v1/perturbations/cmpds_names/batch_0487.json

Processing:   9%|▉         | 83/947 [02:13<16:28,  1.14s/it]

Saved batch 254 to ../../data/curation_v1/perturbations/cmpds_names/batch_0254.json

Processing:   9%|▉         | 84/947 [02:14<16:00,  1.11s/it]

Saved batch 29 to ../../data/curation_v1/perturbations/cmpds_names/batch_0029.json

Processing:   9%|▉         | 85/947 [02:15<13:11,  1.09it/s]

Saved batch 643 to ../../data/curation_v1/perturbations/cmpds_names/batch_0643.json
Saved batch 800 to ../../data/curation_v1/perturbations/cmpds_names/batch_0800.json

Processing:   9%|▉         | 87/947 [02:15<08:12,  1.75it/s]

Saved batch 98 to ../../data/curation_v1/perturbations/cmpds_names/batch_0098.json

Processing:   9%|▉         | 88/947 [02:17<14:24,  1.01s/it]

Saved batch 488 to ../../data/curation_v1/perturbations/cmpds_names/batch_0488.json

Processing:   9%|▉         | 89/947 [02:18<13:11,  1.08it/s]

Saved batch 878 to ../../data/curation_v1/perturbations/cmpds_names/batch_0878.json

Processing:  10%|▉         | 90/947 [02:18<10:55,  1.31it/s]

Saved batch 877 to ../../data/curation_v1/perturbations/cmpds_names/batch_0877.json

Processing:  10%|▉         | 91/947 [02:20<12:30,  1.14it/s]

Saved batch 644 to ../../data/curation_v1/perturbations/cmpds_names/batch_0644.json
Saved batch 255 to ../../data/curation_v1/perturbations/cmpds_names/batch_0255.json

Processing:  10%|▉         | 93/947 [02:20<08:16,  1.72it/s]

Saved batch 801 to ../../data/curation_v1/perturbations/cmpds_names/batch_0801.json

Processing:  10%|█         | 95/947 [02:21<06:53,  2.06it/s]

Saved batch 28 to ../../data/curation_v1/perturbations/cmpds_names/batch_0028.json
Saved batch 489 to ../../data/curation_v1/perturbations/cmpds_names/batch_0489.json

Processing:  10%|█         | 96/947 [02:23<15:06,  1.06s/it]

Saved batch 256 to ../../data/curation_v1/perturbations/cmpds_names/batch_0256.json

Processing:  10%|█         | 97/947 [02:25<17:08,  1.21s/it]

Saved batch 645 to ../../data/curation_v1/perturbations/cmpds_names/batch_0645.json

Processing:  10%|█         | 98/947 [02:25<13:16,  1.07it/s]

Saved batch 880 to ../../data/curation_v1/perturbations/cmpds_names/batch_0880.json

Processing:  10%|█         | 99/947 [02:26<10:36,  1.33it/s]

Saved batch 802 to ../../data/curation_v1/perturbations/cmpds_names/batch_0802.json

Processing:  11%|█         | 100/947 [02:26<08:41,  1.62it/s]

Saved batch 27 to ../../data/curation_v1/perturbations/cmpds_names/batch_0027.json

Processing:  11%|█         | 101/947 [02:27<12:07,  1.16it/s]

Saved batch 490 to ../../data/curation_v1/perturbations/cmpds_names/batch_0490.json

Processing:  11%|█         | 102/947 [02:28<13:20,  1.06it/s]

Saved batch 879 to ../../data/curation_v1/perturbations/cmpds_names/batch_0879.json

Processing:  11%|█         | 103/947 [02:31<18:58,  1.35s/it]

Saved batch 99 to ../../data/curation_v1/perturbations/cmpds_names/batch_0099.json

Processing:  11%|█         | 104/947 [02:36<36:17,  2.58s/it]

Saved batch 491 to ../../data/curation_v1/perturbations/cmpds_names/batch_0491.json

Processing:  11%|█         | 105/947 [02:37<27:45,  1.98s/it]

Saved batch 100 to ../../data/curation_v1/perturbations/cmpds_names/batch_0100.json

Processing:  11%|█         | 106/947 [02:38<23:28,  1.68s/it]

Saved batch 647 to ../../data/curation_v1/perturbations/cmpds_names/batch_0647.json
Saved batch 257 to ../../data/curation_v1/perturbations/cmpds_names/batch_0257.json

Processing:  11%|█▏        | 108/947 [02:38<13:21,  1.05it/s]

Saved batch 26 to ../../data/curation_v1/perturbations/cmpds_names/batch_0026.json

Processing:  12%|█▏        | 109/947 [02:38<10:51,  1.29it/s]

Saved batch 803 to ../../data/curation_v1/perturbations/cmpds_names/batch_0803.json

Processing:  12%|█▏        | 110/947 [02:38<08:45,  1.59it/s]

Saved batch 101 to ../../data/curation_v1/perturbations/cmpds_names/batch_0101.json

Processing:  12%|█▏        | 111/947 [02:40<11:02,  1.26it/s]

Saved batch 881 to ../../data/curation_v1/perturbations/cmpds_names/batch_0881.json

Processing:  12%|█▏        | 112/947 [02:43<21:54,  1.57s/it]

Saved batch 258 to ../../data/curation_v1/perturbations/cmpds_names/batch_0258.json

Processing:  12%|█▏        | 113/947 [02:44<17:47,  1.28s/it]

Saved batch 102 to ../../data/curation_v1/perturbations/cmpds_names/batch_0102.json

Processing:  12%|█▏        | 114/947 [02:45<15:46,  1.14s/it]

Saved batch 646 to ../../data/curation_v1/perturbations/cmpds_names/batch_0646.json

Processing:  12%|█▏        | 115/947 [02:45<12:05,  1.15it/s]

Saved batch 25 to ../../data/curation_v1/perturbations/cmpds_names/batch_0025.json

Processing:  12%|█▏        | 116/947 [02:46<13:12,  1.05it/s]

Saved batch 804 to ../../data/curation_v1/perturbations/cmpds_names/batch_0804.json

Processing:  12%|█▏        | 117/947 [02:46<10:42,  1.29it/s]

Saved batch 648 to ../../data/curation_v1/perturbations/cmpds_names/batch_0648.json

Processing:  13%|█▎        | 119/947 [02:47<07:18,  1.89it/s]

Saved batch 492 to ../../data/curation_v1/perturbations/cmpds_names/batch_0492.json
Saved batch 882 to ../../data/curation_v1/perturbations/cmpds_names/batch_0882.json

Processing:  13%|█▎        | 120/947 [02:50<16:48,  1.22s/it]

Saved batch 24 to ../../data/curation_v1/perturbations/cmpds_names/batch_0024.json

Processing:  13%|█▎        | 121/947 [02:51<16:53,  1.23s/it]

Saved batch 103 to ../../data/curation_v1/perturbations/cmpds_names/batch_0103.json

Processing:  13%|█▎        | 122/947 [02:52<15:34,  1.13s/it]

Saved batch 493 to ../../data/curation_v1/perturbations/cmpds_names/batch_0493.json

Processing:  13%|█▎        | 123/947 [02:52<11:46,  1.17it/s]

Saved batch 259 to ../../data/curation_v1/perturbations/cmpds_names/batch_0259.json

Processing:  13%|█▎        | 124/947 [02:53<11:37,  1.18it/s]

Saved batch 649 to ../../data/curation_v1/perturbations/cmpds_names/batch_0649.json

Processing:  13%|█▎        | 125/947 [02:54<10:52,  1.26it/s]

Saved batch 260 to ../../data/curation_v1/perturbations/cmpds_names/batch_0260.json

Processing:  13%|█▎        | 127/947 [02:55<08:06,  1.69it/s]

Saved batch 23 to ../../data/curation_v1/perturbations/cmpds_names/batch_0023.json
Saved batch 805 to ../../data/curation_v1/perturbations/cmpds_names/batch_0805.json

Processing:  14%|█▎        | 129/947 [02:57<12:18,  1.11it/s]

Saved batch 494 to ../../data/curation_v1/perturbations/cmpds_names/batch_0494.json
Saved batch 806 to ../../data/curation_v1/perturbations/cmpds_names/batch_0806.json

Processing:  14%|█▎        | 130/947 [02:59<15:35,  1.14s/it]

Saved batch 104 to ../../data/curation_v1/perturbations/cmpds_names/batch_0104.json

Processing:  14%|█▍        | 131/947 [03:00<14:11,  1.04s/it]

Saved batch 261 to ../../data/curation_v1/perturbations/cmpds_names/batch_0261.json

Processing:  14%|█▍        | 133/947 [03:01<10:07,  1.34it/s]

Saved batch 883 to ../../data/curation_v1/perturbations/cmpds_names/batch_0883.json
Saved batch 495 to ../../data/curation_v1/perturbations/cmpds_names/batch_0495.json

Processing:  14%|█▍        | 134/947 [03:03<14:52,  1.10s/it]

Saved batch 884 to ../../data/curation_v1/perturbations/cmpds_names/batch_0884.json

Processing:  14%|█▍        | 135/947 [03:05<17:19,  1.28s/it]

Saved batch 22 to ../../data/curation_v1/perturbations/cmpds_names/batch_0022.json

Processing:  14%|█▍        | 136/947 [03:05<13:55,  1.03s/it]

Saved batch 650 to ../../data/curation_v1/perturbations/cmpds_names/batch_0650.json

Processing:  14%|█▍        | 137/947 [03:06<13:43,  1.02s/it]

Saved batch 885 to ../../data/curation_v1/perturbations/cmpds_names/batch_0885.json

Processing:  15%|█▍        | 138/947 [03:07<13:14,  1.02it/s]

Saved batch 262 to ../../data/curation_v1/perturbations/cmpds_names/batch_0262.json

Processing:  15%|█▍        | 139/947 [03:08<11:43,  1.15it/s]

Saved batch 651 to ../../data/curation_v1/perturbations/cmpds_names/batch_0651.json

Processing:  15%|█▍        | 140/947 [03:08<11:15,  1.19it/s]

Saved batch 496 to ../../data/curation_v1/perturbations/cmpds_names/batch_0496.json

Processing:  15%|█▌        | 143/947 [03:12<13:18,  1.01it/s]

Saved batch 106 to ../../data/curation_v1/perturbations/cmpds_names/batch_0106.json
Saved batch 263 to ../../data/curation_v1/perturbations/cmpds_names/batch_0263.json
Saved batch 107 to ../../data/curation_v1/perturbations/cmpds_names/batch_0107.json

Processing:  15%|█▌        | 144/947 [03:15<16:57,  1.27s/it]

Saved batch 21 to ../../data/curation_v1/perturbations/cmpds_names/batch_0021.json

Processing:  15%|█▌        | 145/947 [03:15<15:37,  1.17s/it]

Saved batch 20 to ../../data/curation_v1/perturbations/cmpds_names/batch_0020.json

Processing:  15%|█▌        | 146/947 [03:16<13:25,  1.01s/it]

Saved batch 808 to ../../data/curation_v1/perturbations/cmpds_names/batch_0808.json
Saved batch 886 to ../../data/curation_v1/perturbations/cmpds_names/batch_0886.json

Processing:  16%|█▌        | 148/947 [03:18<14:17,  1.07s/it]

Saved batch 497 to ../../data/curation_v1/perturbations/cmpds_names/batch_0497.json

Processing:  16%|█▌        | 149/947 [03:19<12:06,  1.10it/s]

Saved batch 652 to ../../data/curation_v1/perturbations/cmpds_names/batch_0652.json

Processing:  16%|█▌        | 150/947 [03:20<13:04,  1.02it/s]

Saved batch 653 to ../../data/curation_v1/perturbations/cmpds_names/batch_0653.json
Saved batch 807 to ../../data/curation_v1/perturbations/cmpds_names/batch_0807.json

Processing:  16%|█▌        | 152/947 [03:20<08:12,  1.61it/s]

Saved batch 809 to ../../data/curation_v1/perturbations/cmpds_names/batch_0809.json

Processing:  16%|█▌        | 153/947 [03:23<15:10,  1.15s/it]

Saved batch 108 to ../../data/curation_v1/perturbations/cmpds_names/batch_0108.json

Processing:  16%|█▋        | 154/947 [03:24<14:48,  1.12s/it]

Saved batch 264 to ../../data/curation_v1/perturbations/cmpds_names/batch_0264.json

Processing:  16%|█▋        | 155/947 [03:25<13:55,  1.05s/it]

Saved batch 105 to ../../data/curation_v1/perturbations/cmpds_names/batch_0105.json

Processing:  16%|█▋        | 156/947 [03:25<12:02,  1.09it/s]

Saved batch 498 to ../../data/curation_v1/perturbations/cmpds_names/batch_0498.json

Processing:  17%|█▋        | 157/947 [03:26<11:08,  1.18it/s]

Saved batch 654 to ../../data/curation_v1/perturbations/cmpds_names/batch_0654.json

Processing:  17%|█▋        | 158/947 [03:28<15:19,  1.17s/it]

Saved batch 810 to ../../data/curation_v1/perturbations/cmpds_names/batch_0810.json

Processing:  17%|█▋        | 160/947 [03:29<11:29,  1.14it/s]

Saved batch 888 to ../../data/curation_v1/perturbations/cmpds_names/batch_0888.json
Saved batch 887 to ../../data/curation_v1/perturbations/cmpds_names/batch_0887.json
Saved batch 109 to ../../data/curation_v1/perturbations/cmpds_names/batch_0109.json

Processing:  17%|█▋        | 162/947 [03:30<08:57,  1.46it/s]

Saved batch 265 to ../../data/curation_v1/perturbations/cmpds_names/batch_0265.json

Processing:  17%|█▋        | 164/947 [03:31<06:28,  2.02it/s]

Saved batch 811 to ../../data/curation_v1/perturbations/cmpds_names/batch_0811.json
Saved batch 33 to ../../data/curation_v1/perturbations/cmpds_names/batch_0033.json

Processing:  17%|█▋        | 165/947 [03:31<06:33,  1.99it/s]

Saved batch 499 to ../../data/curation_v1/perturbations/cmpds_names/batch_0499.json

Processing:  18%|█▊        | 166/947 [03:34<13:40,  1.05s/it]

Saved batch 655 to ../../data/curation_v1/perturbations/cmpds_names/batch_0655.json

Processing:  18%|█▊        | 167/947 [03:35<13:10,  1.01s/it]

Saved batch 37 to ../../data/curation_v1/perturbations/cmpds_names/batch_0037.json

Processing:  18%|█▊        | 168/947 [03:35<11:16,  1.15it/s]

Saved batch 38 to ../../data/curation_v1/perturbations/cmpds_names/batch_0038.json

Processing:  18%|█▊        | 169/947 [03:38<19:47,  1.53s/it]

Saved batch 812 to ../../data/curation_v1/perturbations/cmpds_names/batch_0812.json

Processing:  18%|█▊        | 170/947 [03:39<16:14,  1.25s/it]

Saved batch 110 to ../../data/curation_v1/perturbations/cmpds_names/batch_0110.json
Saved batch 266 to ../../data/curation_v1/perturbations/cmpds_names/batch_0266.json

Processing:  18%|█▊        | 172/947 [03:41<14:10,  1.10s/it]

Saved batch 889 to ../../data/curation_v1/perturbations/cmpds_names/batch_0889.json

Processing:  18%|█▊        | 173/947 [03:41<11:27,  1.13it/s]

Saved batch 111 to ../../data/curation_v1/perturbations/cmpds_names/batch_0111.json

Processing:  18%|█▊        | 174/947 [03:42<12:01,  1.07it/s]

Saved batch 267 to ../../data/curation_v1/perturbations/cmpds_names/batch_0267.json

Processing:  18%|█▊        | 175/947 [03:43<10:12,  1.26it/s]

Saved batch 656 to ../../data/curation_v1/perturbations/cmpds_names/batch_0656.json
Saved batch 500 to ../../data/curation_v1/perturbations/cmpds_names/batch_0500.json

Processing:  19%|█▊        | 177/947 [03:45<11:52,  1.08it/s]

Saved batch 890 to ../../data/curation_v1/perturbations/cmpds_names/batch_0890.json

Processing:  19%|█▉        | 178/947 [03:45<10:46,  1.19it/s]

Saved batch 657 to ../../data/curation_v1/perturbations/cmpds_names/batch_0657.json

Processing:  19%|█▉        | 179/947 [03:48<16:17,  1.27s/it]

Saved batch 268 to ../../data/curation_v1/perturbations/cmpds_names/batch_0268.json

Processing:  19%|█▉        | 180/947 [03:49<14:50,  1.16s/it]

Saved batch 813 to ../../data/curation_v1/perturbations/cmpds_names/batch_0813.json

Processing:  19%|█▉        | 181/947 [03:50<15:57,  1.25s/it]

Saved batch 501 to ../../data/curation_v1/perturbations/cmpds_names/batch_0501.json
Saved batch 36 to ../../data/curation_v1/perturbations/cmpds_names/batch_0036.json

Processing:  19%|█▉        | 183/947 [03:51<09:53,  1.29it/s]

Saved batch 35 to ../../data/curation_v1/perturbations/cmpds_names/batch_0035.json

Processing:  19%|█▉        | 184/947 [03:52<11:22,  1.12it/s]

Saved batch 658 to ../../data/curation_v1/perturbations/cmpds_names/batch_0658.json

Processing:  20%|█▉        | 186/947 [03:53<08:49,  1.44it/s]

Saved batch 34 to ../../data/curation_v1/perturbations/cmpds_names/batch_0034.json
Saved batch 814 to ../../data/curation_v1/perturbations/cmpds_names/batch_0814.json

Processing:  20%|█▉        | 188/947 [03:53<05:25,  2.33it/s]

Saved batch 112 to ../../data/curation_v1/perturbations/cmpds_names/batch_0112.json
Saved batch 891 to ../../data/curation_v1/perturbations/cmpds_names/batch_0891.json

Processing:  20%|█▉        | 189/947 [03:55<10:52,  1.16it/s]

Saved batch 502 to ../../data/curation_v1/perturbations/cmpds_names/batch_0502.json

Processing:  20%|██        | 190/947 [03:57<12:14,  1.03it/s]

Saved batch 113 to ../../data/curation_v1/perturbations/cmpds_names/batch_0113.json

Processing:  20%|██        | 191/947 [04:00<20:23,  1.62s/it]

Saved batch 815 to ../../data/curation_v1/perturbations/cmpds_names/batch_0815.json

Processing:  20%|██        | 192/947 [04:01<18:36,  1.48s/it]

Saved batch 270 to ../../data/curation_v1/perturbations/cmpds_names/batch_0270.json

Processing:  20%|██        | 194/947 [04:02<10:52,  1.15it/s]

Saved batch 504 to ../../data/curation_v1/perturbations/cmpds_names/batch_0504.json
Saved batch 659 to ../../data/curation_v1/perturbations/cmpds_names/batch_0659.json

Processing:  21%|██        | 195/947 [04:03<12:45,  1.02s/it]

Saved batch 503 to ../../data/curation_v1/perturbations/cmpds_names/batch_0503.json

Processing:  21%|██        | 196/947 [04:03<10:31,  1.19it/s]

Saved batch 114 to ../../data/curation_v1/perturbations/cmpds_names/batch_0114.json

Processing:  21%|██        | 197/947 [04:04<09:15,  1.35it/s]

Saved batch 892 to ../../data/curation_v1/perturbations/cmpds_names/batch_0892.json

Processing:  21%|██        | 198/947 [04:05<08:34,  1.46it/s]

Saved batch 32 to ../../data/curation_v1/perturbations/cmpds_names/batch_0032.json
Saved batch 269 to ../../data/curation_v1/perturbations/cmpds_names/batch_0269.json

Processing:  21%|██        | 200/947 [04:06<09:29,  1.31it/s]

Saved batch 893 to ../../data/curation_v1/perturbations/cmpds_names/batch_0893.json

Processing:  21%|██        | 201/947 [04:08<11:20,  1.10it/s]

Saved batch 660 to ../../data/curation_v1/perturbations/cmpds_names/batch_0660.json

Processing:  21%|██▏       | 202/947 [04:08<09:08,  1.36it/s]

Saved batch 43 to ../../data/curation_v1/perturbations/cmpds_names/batch_0043.json

Processing:  21%|██▏       | 203/947 [04:08<08:01,  1.54it/s]

Saved batch 816 to ../../data/curation_v1/perturbations/cmpds_names/batch_0816.json

Processing:  22%|██▏       | 204/947 [04:10<10:59,  1.13it/s]

Saved batch 115 to ../../data/curation_v1/perturbations/cmpds_names/batch_0115.json

Processing:  22%|██▏       | 205/947 [04:12<14:42,  1.19s/it]

Saved batch 271 to ../../data/curation_v1/perturbations/cmpds_names/batch_0271.json

Processing:  22%|██▏       | 206/947 [04:14<18:37,  1.51s/it]

Saved batch 272 to ../../data/curation_v1/perturbations/cmpds_names/batch_0272.json

Processing:  22%|██▏       | 207/947 [04:15<18:28,  1.50s/it]

Saved batch 661 to ../../data/curation_v1/perturbations/cmpds_names/batch_0661.json

Processing:  22%|██▏       | 208/947 [04:17<18:09,  1.47s/it]

Saved batch 817 to ../../data/curation_v1/perturbations/cmpds_names/batch_0817.json

Processing:  22%|██▏       | 209/947 [04:18<18:02,  1.47s/it]

Saved batch 505 to ../../data/curation_v1/perturbations/cmpds_names/batch_0505.json

Processing:  22%|██▏       | 210/947 [04:19<15:24,  1.25s/it]

Saved batch 506 to ../../data/curation_v1/perturbations/cmpds_names/batch_0506.json

Processing:  22%|██▏       | 211/947 [04:20<14:30,  1.18s/it]

Saved batch 116 to ../../data/curation_v1/perturbations/cmpds_names/batch_0116.json

Processing:  22%|██▏       | 213/947 [04:21<08:52,  1.38it/s]

Saved batch 818 to ../../data/curation_v1/perturbations/cmpds_names/batch_0818.json
Saved batch 40 to ../../data/curation_v1/perturbations/cmpds_names/batch_0040.json

Processing:  23%|██▎       | 214/947 [04:22<09:18,  1.31it/s]

Saved batch 895 to ../../data/curation_v1/perturbations/cmpds_names/batch_0895.json

Processing:  23%|██▎       | 215/947 [04:23<12:20,  1.01s/it]

Saved batch 894 to ../../data/curation_v1/perturbations/cmpds_names/batch_0894.json

Processing:  23%|██▎       | 216/947 [04:23<09:46,  1.25it/s]

Saved batch 662 to ../../data/curation_v1/perturbations/cmpds_names/batch_0662.json

Processing:  23%|██▎       | 217/947 [04:26<15:56,  1.31s/it]

Saved batch 896 to ../../data/curation_v1/perturbations/cmpds_names/batch_0896.json

Processing:  23%|██▎       | 219/947 [04:27<10:31,  1.15it/s]

Saved batch 117 to ../../data/curation_v1/perturbations/cmpds_names/batch_0117.json
Saved batch 42 to ../../data/curation_v1/perturbations/cmpds_names/batch_0042.json

Processing:  23%|██▎       | 220/947 [04:30<16:38,  1.37s/it]

Saved batch 507 to ../../data/curation_v1/perturbations/cmpds_names/batch_0507.json

Processing:  23%|██▎       | 222/947 [04:30<09:56,  1.21it/s]

Saved batch 819 to ../../data/curation_v1/perturbations/cmpds_names/batch_0819.json
Saved batch 118 to ../../data/curation_v1/perturbations/cmpds_names/batch_0118.json

Processing:  24%|██▎       | 223/947 [04:32<12:11,  1.01s/it]

Saved batch 897 to ../../data/curation_v1/perturbations/cmpds_names/batch_0897.json

Processing:  24%|██▎       | 224/947 [04:32<09:24,  1.28it/s]

Saved batch 274 to ../../data/curation_v1/perturbations/cmpds_names/batch_0274.json

Processing:  24%|██▍       | 225/947 [04:33<11:29,  1.05it/s]

Saved batch 663 to ../../data/curation_v1/perturbations/cmpds_names/batch_0663.json

Processing:  24%|██▍       | 226/947 [04:34<10:44,  1.12it/s]

Saved batch 664 to ../../data/curation_v1/perturbations/cmpds_names/batch_0664.json
Saved batch 273 to ../../data/curation_v1/perturbations/cmpds_names/batch_0273.json

Processing:  24%|██▍       | 228/947 [04:34<06:54,  1.74it/s]

Saved batch 41 to ../../data/curation_v1/perturbations/cmpds_names/batch_0041.json

Processing:  24%|██▍       | 230/947 [04:35<04:40,  2.56it/s]

Saved batch 898 to ../../data/curation_v1/perturbations/cmpds_names/batch_0898.json
Saved batch 820 to ../../data/curation_v1/perturbations/cmpds_names/batch_0820.json

Processing:  24%|██▍       | 232/947 [04:36<06:31,  1.83it/s]

Saved batch 508 to ../../data/curation_v1/perturbations/cmpds_names/batch_0508.json
Saved batch 275 to ../../data/curation_v1/perturbations/cmpds_names/batch_0275.json

Processing:  25%|██▍       | 233/947 [04:40<18:02,  1.52s/it]

Saved batch 821 to ../../data/curation_v1/perturbations/cmpds_names/batch_0821.json

Processing:  25%|██▍       | 234/947 [04:41<15:18,  1.29s/it]

Saved batch 509 to ../../data/curation_v1/perturbations/cmpds_names/batch_0509.json

Processing:  25%|██▍       | 236/947 [04:43<11:24,  1.04it/s]

Saved batch 119 to ../../data/curation_v1/perturbations/cmpds_names/batch_0119.json
Saved batch 899 to ../../data/curation_v1/perturbations/cmpds_names/batch_0899.json

Processing:  25%|██▌       | 237/947 [04:43<09:34,  1.24it/s]

Saved batch 665 to ../../data/curation_v1/perturbations/cmpds_names/batch_0665.json

Processing:  25%|██▌       | 238/947 [04:43<07:59,  1.48it/s]

Saved batch 39 to ../../data/curation_v1/perturbations/cmpds_names/batch_0039.json

Processing:  25%|██▌       | 239/947 [04:44<07:09,  1.65it/s]

Saved batch 47 to ../../data/curation_v1/perturbations/cmpds_names/batch_0047.json

Processing:  25%|██▌       | 240/947 [04:46<12:49,  1.09s/it]

Saved batch 276 to ../../data/curation_v1/perturbations/cmpds_names/batch_0276.json

Processing:  25%|██▌       | 241/947 [04:47<13:00,  1.11s/it]

Saved batch 120 to ../../data/curation_v1/perturbations/cmpds_names/batch_0120.json

Processing:  26%|██▌       | 242/947 [04:48<11:50,  1.01s/it]

Saved batch 822 to ../../data/curation_v1/perturbations/cmpds_names/batch_0822.json

Processing:  26%|██▌       | 243/947 [04:48<09:50,  1.19it/s]

Saved batch 666 to ../../data/curation_v1/perturbations/cmpds_names/batch_0666.json

Processing:  26%|██▌       | 244/947 [04:49<08:38,  1.36it/s]

Saved batch 900 to ../../data/curation_v1/perturbations/cmpds_names/batch_0900.json

Processing:  26%|██▌       | 245/947 [04:49<06:51,  1.71it/s]

Saved batch 510 to ../../data/curation_v1/perturbations/cmpds_names/batch_0510.json

Processing:  26%|██▌       | 246/947 [04:50<08:39,  1.35it/s]

Saved batch 277 to ../../data/curation_v1/perturbations/cmpds_names/batch_0277.json

Processing:  26%|██▌       | 247/947 [04:51<09:36,  1.21it/s]

Saved batch 46 to ../../data/curation_v1/perturbations/cmpds_names/batch_0046.json

Processing:  26%|██▌       | 248/947 [04:52<09:13,  1.26it/s]

Saved batch 121 to ../../data/curation_v1/perturbations/cmpds_names/batch_0121.json

Processing:  26%|██▋       | 249/947 [04:57<23:25,  2.01s/it]

Saved batch 901 to ../../data/curation_v1/perturbations/cmpds_names/batch_0901.json

Processing:  26%|██▋       | 250/947 [04:57<18:27,  1.59s/it]

Saved batch 511 to ../../data/curation_v1/perturbations/cmpds_names/batch_0511.json

Processing:  27%|██▋       | 252/947 [04:58<11:43,  1.01s/it]

Saved batch 45 to ../../data/curation_v1/perturbations/cmpds_names/batch_0045.json
Saved batch 823 to ../../data/curation_v1/perturbations/cmpds_names/batch_0823.json

Processing:  27%|██▋       | 253/947 [04:59<08:58,  1.29it/s]

Saved batch 667 to ../../data/curation_v1/perturbations/cmpds_names/batch_0667.json

Processing:  27%|██▋       | 255/947 [05:00<07:11,  1.60it/s]

Saved batch 668 to ../../data/curation_v1/perturbations/cmpds_names/batch_0668.json
Saved batch 512 to ../../data/curation_v1/perturbations/cmpds_names/batch_0512.json

Processing:  27%|██▋       | 256/947 [05:00<07:18,  1.57it/s]

Saved batch 122 to ../../data/curation_v1/perturbations/cmpds_names/batch_0122.json
Saved batch 278 to ../../data/curation_v1/perturbations/cmpds_names/batch_0278.json

Processing:  27%|██▋       | 258/947 [05:02<07:27,  1.54it/s]

Saved batch 824 to ../../data/curation_v1/perturbations/cmpds_names/batch_0824.json

Processing:  27%|██▋       | 259/947 [05:04<10:52,  1.06it/s]

Saved batch 279 to ../../data/curation_v1/perturbations/cmpds_names/batch_0279.json

Processing:  27%|██▋       | 260/947 [05:05<12:09,  1.06s/it]

Saved batch 825 to ../../data/curation_v1/perturbations/cmpds_names/batch_0825.json

Processing:  28%|██▊       | 261/947 [05:07<13:27,  1.18s/it]

Saved batch 669 to ../../data/curation_v1/perturbations/cmpds_names/batch_0669.json

Processing:  28%|██▊       | 262/947 [05:07<11:51,  1.04s/it]

Saved batch 513 to ../../data/curation_v1/perturbations/cmpds_names/batch_0513.json

Processing:  28%|██▊       | 263/947 [05:09<13:37,  1.20s/it]

Saved batch 902 to ../../data/curation_v1/perturbations/cmpds_names/batch_0902.json

Processing:  28%|██▊       | 264/947 [05:09<10:23,  1.09it/s]

Saved batch 44 to ../../data/curation_v1/perturbations/cmpds_names/batch_0044.json

Processing:  28%|██▊       | 266/947 [05:10<07:38,  1.48it/s]

Saved batch 48 to ../../data/curation_v1/perturbations/cmpds_names/batch_0048.json
Saved batch 123 to ../../data/curation_v1/perturbations/cmpds_names/batch_0123.json

Processing:  28%|██▊       | 267/947 [05:12<12:06,  1.07s/it]

Saved batch 124 to ../../data/curation_v1/perturbations/cmpds_names/batch_0124.json
Saved batch 903 to ../../data/curation_v1/perturbations/cmpds_names/batch_0903.json

Processing:  28%|██▊       | 269/947 [05:13<10:04,  1.12it/s]

Saved batch 514 to ../../data/curation_v1/perturbations/cmpds_names/batch_0514.json

Processing:  29%|██▊       | 270/947 [05:14<08:35,  1.31it/s]

Saved batch 826 to ../../data/curation_v1/perturbations/cmpds_names/batch_0826.json

Processing:  29%|██▊       | 271/947 [05:15<10:41,  1.05it/s]

Saved batch 280 to ../../data/curation_v1/perturbations/cmpds_names/batch_0280.json

Processing:  29%|██▊       | 272/947 [05:17<13:11,  1.17s/it]

Saved batch 125 to ../../data/curation_v1/perturbations/cmpds_names/batch_0125.json

Processing:  29%|██▉       | 273/947 [05:18<11:13,  1.00it/s]

Saved batch 670 to ../../data/curation_v1/perturbations/cmpds_names/batch_0670.json

Processing:  29%|██▉       | 274/947 [05:18<09:34,  1.17it/s]

Saved batch 281 to ../../data/curation_v1/perturbations/cmpds_names/batch_0281.json

Processing:  29%|██▉       | 275/947 [05:19<08:44,  1.28it/s]

Saved batch 74 to ../../data/curation_v1/perturbations/cmpds_names/batch_0074.json

Processing:  29%|██▉       | 276/947 [05:21<14:57,  1.34s/it]

Saved batch 515 to ../../data/curation_v1/perturbations/cmpds_names/batch_0515.json

Processing:  29%|██▉       | 277/947 [05:22<11:28,  1.03s/it]

Saved batch 671 to ../../data/curation_v1/perturbations/cmpds_names/batch_0671.json

Processing:  29%|██▉       | 278/947 [05:23<11:25,  1.02s/it]

Saved batch 827 to ../../data/curation_v1/perturbations/cmpds_names/batch_0827.json
Saved batch 72 to ../../data/curation_v1/perturbations/cmpds_names/batch_0072.json

Processing:  30%|██▉       | 280/947 [05:24<09:37,  1.16it/s]

Saved batch 282 to ../../data/curation_v1/perturbations/cmpds_names/batch_0282.json

Processing:  30%|██▉       | 281/947 [05:25<09:28,  1.17it/s]

Saved batch 672 to ../../data/curation_v1/perturbations/cmpds_names/batch_0672.json

Processing:  30%|██▉       | 282/947 [05:25<07:43,  1.44it/s]

Saved batch 126 to ../../data/curation_v1/perturbations/cmpds_names/batch_0126.json

Processing:  30%|██▉       | 283/947 [05:27<10:31,  1.05it/s]

Saved batch 905 to ../../data/curation_v1/perturbations/cmpds_names/batch_0905.json

Processing:  30%|██▉       | 284/947 [05:27<08:33,  1.29it/s]

Saved batch 516 to ../../data/curation_v1/perturbations/cmpds_names/batch_0516.json

Processing:  30%|███       | 286/947 [05:28<06:33,  1.68it/s]

Saved batch 904 to ../../data/curation_v1/perturbations/cmpds_names/batch_0904.json
Saved batch 73 to ../../data/curation_v1/perturbations/cmpds_names/batch_0073.json

Processing:  30%|███       | 287/947 [05:29<07:06,  1.55it/s]

Saved batch 906 to ../../data/curation_v1/perturbations/cmpds_names/batch_0906.json

Processing:  30%|███       | 288/947 [05:30<09:39,  1.14it/s]

Saved batch 283 to ../../data/curation_v1/perturbations/cmpds_names/batch_0283.json

Processing:  31%|███       | 289/947 [05:32<12:08,  1.11s/it]

Saved batch 828 to ../../data/curation_v1/perturbations/cmpds_names/batch_0828.json

Processing:  31%|███       | 290/947 [05:33<11:33,  1.06s/it]

Saved batch 128 to ../../data/curation_v1/perturbations/cmpds_names/batch_0128.json

Processing:  31%|███       | 291/947 [05:33<09:31,  1.15it/s]

Saved batch 673 to ../../data/curation_v1/perturbations/cmpds_names/batch_0673.json

Processing:  31%|███       | 292/947 [05:33<07:42,  1.42it/s]

Saved batch 127 to ../../data/curation_v1/perturbations/cmpds_names/batch_0127.json

Processing:  31%|███       | 293/947 [05:35<09:23,  1.16it/s]

Saved batch 907 to ../../data/curation_v1/perturbations/cmpds_names/batch_0907.json
Saved batch 517 to ../../data/curation_v1/perturbations/cmpds_names/batch_0517.json

Processing:  31%|███       | 295/947 [05:36<09:04,  1.20it/s]

Saved batch 284 to ../../data/curation_v1/perturbations/cmpds_names/batch_0284.json

Processing:  31%|███▏      | 296/947 [05:39<13:52,  1.28s/it]

Saved batch 129 to ../../data/curation_v1/perturbations/cmpds_names/batch_0129.json

Processing:  31%|███▏      | 297/947 [05:40<13:45,  1.27s/it]

Saved batch 829 to ../../data/curation_v1/perturbations/cmpds_names/batch_0829.json

Processing:  31%|███▏      | 298/947 [05:42<14:04,  1.30s/it]

Saved batch 908 to ../../data/curation_v1/perturbations/cmpds_names/batch_0908.json
Saved batch 49 to ../../data/curation_v1/perturbations/cmpds_names/batch_0049.json

Processing:  32%|███▏      | 300/947 [05:46<17:38,  1.64s/it]

Saved batch 519 to ../../data/curation_v1/perturbations/cmpds_names/batch_0519.json

Processing:  32%|███▏      | 301/947 [05:47<15:33,  1.44s/it]

Saved batch 675 to ../../data/curation_v1/perturbations/cmpds_names/batch_0675.json
Saved batch 830 to ../../data/curation_v1/perturbations/cmpds_names/batch_0830.json

Processing:  32%|███▏      | 303/947 [05:48<13:14,  1.23s/it]

Saved batch 674 to ../../data/curation_v1/perturbations/cmpds_names/batch_0674.json

Processing:  32%|███▏      | 304/947 [05:49<11:09,  1.04s/it]

Saved batch 518 to ../../data/curation_v1/perturbations/cmpds_names/batch_0518.json
Saved batch 54 to ../../data/curation_v1/perturbations/cmpds_names/batch_0054.json

Processing:  32%|███▏      | 306/947 [05:50<09:48,  1.09it/s]

Saved batch 285 to ../../data/curation_v1/perturbations/cmpds_names/batch_0285.json

Processing:  32%|███▏      | 307/947 [05:54<17:13,  1.61s/it]

Saved batch 676 to ../../data/curation_v1/perturbations/cmpds_names/batch_0676.json

Processing:  33%|███▎      | 308/947 [05:55<15:13,  1.43s/it]

Saved batch 831 to ../../data/curation_v1/perturbations/cmpds_names/batch_0831.json

Processing:  33%|███▎      | 310/947 [05:56<09:33,  1.11it/s]

Saved batch 52 to ../../data/curation_v1/perturbations/cmpds_names/batch_0052.json
Saved batch 286 to ../../data/curation_v1/perturbations/cmpds_names/batch_0286.json

Processing:  33%|███▎      | 311/947 [05:57<09:22,  1.13it/s]

Saved batch 910 to ../../data/curation_v1/perturbations/cmpds_names/batch_0910.json

Processing:  33%|███▎      | 312/947 [05:57<08:24,  1.26it/s]

Saved batch 130 to ../../data/curation_v1/perturbations/cmpds_names/batch_0130.json

Processing:  33%|███▎      | 313/947 [05:58<09:24,  1.12it/s]

Saved batch 53 to ../../data/curation_v1/perturbations/cmpds_names/batch_0053.json

Processing:  33%|███▎      | 314/947 [05:59<07:36,  1.39it/s]

Saved batch 520 to ../../data/curation_v1/perturbations/cmpds_names/batch_0520.json

Processing:  33%|███▎      | 315/947 [06:00<09:16,  1.14it/s]

Saved batch 909 to ../../data/curation_v1/perturbations/cmpds_names/batch_0909.json

Processing:  33%|███▎      | 316/947 [06:02<12:02,  1.14s/it]

Saved batch 131 to ../../data/curation_v1/perturbations/cmpds_names/batch_0131.json

Processing:  33%|███▎      | 317/947 [06:02<09:09,  1.15it/s]

Saved batch 521 to ../../data/curation_v1/perturbations/cmpds_names/batch_0521.json

Processing:  34%|███▎      | 318/947 [06:03<09:09,  1.14it/s]

Saved batch 677 to ../../data/curation_v1/perturbations/cmpds_names/batch_0677.json

Processing:  34%|███▎      | 319/947 [06:03<07:22,  1.42it/s]

Saved batch 287 to ../../data/curation_v1/perturbations/cmpds_names/batch_0287.json

Processing:  34%|███▍      | 320/947 [06:07<18:49,  1.80s/it]

Saved batch 132 to ../../data/curation_v1/perturbations/cmpds_names/batch_0132.json

Processing:  34%|███▍      | 321/947 [06:08<14:47,  1.42s/it]

Saved batch 288 to ../../data/curation_v1/perturbations/cmpds_names/batch_0288.json

Processing:  34%|███▍      | 322/947 [06:08<11:12,  1.08s/it]

Saved batch 833 to ../../data/curation_v1/perturbations/cmpds_names/batch_0833.json

Processing:  34%|███▍      | 323/947 [06:09<11:36,  1.12s/it]

Saved batch 911 to ../../data/curation_v1/perturbations/cmpds_names/batch_0911.json

Processing:  34%|███▍      | 324/947 [06:10<10:10,  1.02it/s]

Saved batch 832 to ../../data/curation_v1/perturbations/cmpds_names/batch_0832.json

Processing:  34%|███▍      | 325/947 [06:11<09:29,  1.09it/s]

Saved batch 912 to ../../data/curation_v1/perturbations/cmpds_names/batch_0912.json

Processing:  34%|███▍      | 326/947 [06:12<11:09,  1.08s/it]

Saved batch 678 to ../../data/curation_v1/perturbations/cmpds_names/batch_0678.json

Processing:  35%|███▍      | 327/947 [06:13<10:46,  1.04s/it]

Saved batch 50 to ../../data/curation_v1/perturbations/cmpds_names/batch_0050.json

Processing:  35%|███▍      | 328/947 [06:14<10:35,  1.03s/it]

Saved batch 522 to ../../data/curation_v1/perturbations/cmpds_names/batch_0522.json

Processing:  35%|███▍      | 329/947 [06:16<11:21,  1.10s/it]

Saved batch 289 to ../../data/curation_v1/perturbations/cmpds_names/batch_0289.json

Processing:  35%|███▍      | 330/947 [06:16<09:18,  1.11it/s]

Saved batch 834 to ../../data/curation_v1/perturbations/cmpds_names/batch_0834.json

Processing:  35%|███▍      | 331/947 [06:17<11:02,  1.08s/it]

Saved batch 133 to ../../data/curation_v1/perturbations/cmpds_names/batch_0133.json

Processing:  35%|███▌      | 332/947 [06:19<13:54,  1.36s/it]

Saved batch 523 to ../../data/curation_v1/perturbations/cmpds_names/batch_0523.json

Processing:  35%|███▌      | 333/947 [06:21<15:18,  1.50s/it]

Saved batch 134 to ../../data/curation_v1/perturbations/cmpds_names/batch_0134.json

Processing:  35%|███▌      | 334/947 [06:21<11:20,  1.11s/it]

Saved batch 71 to ../../data/curation_v1/perturbations/cmpds_names/batch_0071.json

Processing:  35%|███▌      | 335/947 [06:23<12:00,  1.18s/it]

Saved batch 524 to ../../data/curation_v1/perturbations/cmpds_names/batch_0524.json

Processing:  35%|███▌      | 336/947 [06:24<11:15,  1.10s/it]

Saved batch 913 to ../../data/curation_v1/perturbations/cmpds_names/batch_0913.json

Processing:  36%|███▌      | 337/947 [06:26<13:14,  1.30s/it]

Saved batch 680 to ../../data/curation_v1/perturbations/cmpds_names/batch_0680.json

Processing:  36%|███▌      | 338/947 [06:26<10:26,  1.03s/it]

Saved batch 679 to ../../data/curation_v1/perturbations/cmpds_names/batch_0679.json

Processing:  36%|███▌      | 339/947 [06:28<12:26,  1.23s/it]

Saved batch 835 to ../../data/curation_v1/perturbations/cmpds_names/batch_0835.json

Processing:  36%|███▌      | 340/947 [06:28<10:09,  1.00s/it]

Saved batch 290 to ../../data/curation_v1/perturbations/cmpds_names/batch_0290.json
Saved batch 836 to ../../data/curation_v1/perturbations/cmpds_names/batch_0836.json

Processing:  36%|███▌      | 342/947 [06:30<10:21,  1.03s/it]

Saved batch 70 to ../../data/curation_v1/perturbations/cmpds_names/batch_0070.json

Processing:  36%|███▌      | 343/947 [06:31<08:48,  1.14it/s]

Saved batch 291 to ../../data/curation_v1/perturbations/cmpds_names/batch_0291.json

Processing:  36%|███▋      | 345/947 [06:32<06:38,  1.51it/s]

Saved batch 525 to ../../data/curation_v1/perturbations/cmpds_names/batch_0525.json
Saved batch 681 to ../../data/curation_v1/perturbations/cmpds_names/batch_0681.json

Processing:  37%|███▋      | 346/947 [06:32<06:56,  1.44it/s]

Saved batch 69 to ../../data/curation_v1/perturbations/cmpds_names/batch_0069.json

Processing:  37%|███▋      | 347/947 [06:33<08:17,  1.21it/s]

Saved batch 135 to ../../data/curation_v1/perturbations/cmpds_names/batch_0135.json

Processing:  37%|███▋      | 348/947 [06:34<07:32,  1.32it/s]

Saved batch 51 to ../../data/curation_v1/perturbations/cmpds_names/batch_0051.json

Processing:  37%|███▋      | 349/947 [06:35<07:20,  1.36it/s]

Saved batch 914 to ../../data/curation_v1/perturbations/cmpds_names/batch_0914.json

Processing:  37%|███▋      | 350/947 [06:36<09:51,  1.01it/s]

Saved batch 915 to ../../data/curation_v1/perturbations/cmpds_names/batch_0915.json

Processing:  37%|███▋      | 351/947 [06:37<09:36,  1.03it/s]

Saved batch 682 to ../../data/curation_v1/perturbations/cmpds_names/batch_0682.json
Saved batch 526 to ../../data/curation_v1/perturbations/cmpds_names/batch_0526.json

Processing:  37%|███▋      | 353/947 [06:40<10:38,  1.07s/it]

Saved batch 136 to ../../data/curation_v1/perturbations/cmpds_names/batch_0136.json

Processing:  37%|███▋      | 354/947 [06:40<09:01,  1.10it/s]

Saved batch 837 to ../../data/curation_v1/perturbations/cmpds_names/batch_0837.json

Processing:  37%|███▋      | 355/947 [06:40<07:40,  1.28it/s]

Saved batch 292 to ../../data/curation_v1/perturbations/cmpds_names/batch_0292.json

Processing:  38%|███▊      | 356/947 [06:42<09:18,  1.06it/s]

Saved batch 527 to ../../data/curation_v1/perturbations/cmpds_names/batch_0527.json

Processing:  38%|███▊      | 357/947 [06:43<09:02,  1.09it/s]

Saved batch 916 to ../../data/curation_v1/perturbations/cmpds_names/batch_0916.json

Processing:  38%|███▊      | 358/947 [06:44<09:47,  1.00it/s]

Saved batch 59 to ../../data/curation_v1/perturbations/cmpds_names/batch_0059.json

Processing:  38%|███▊      | 359/947 [06:45<08:42,  1.13it/s]

Saved batch 838 to ../../data/curation_v1/perturbations/cmpds_names/batch_0838.json

Processing:  38%|███▊      | 360/947 [06:45<07:43,  1.27it/s]

Saved batch 293 to ../../data/curation_v1/perturbations/cmpds_names/batch_0293.json

Processing:  38%|███▊      | 361/947 [06:47<09:51,  1.01s/it]

Saved batch 137 to ../../data/curation_v1/perturbations/cmpds_names/batch_0137.json

Processing:  38%|███▊      | 362/947 [06:48<12:08,  1.25s/it]

Saved batch 917 to ../../data/curation_v1/perturbations/cmpds_names/batch_0917.json

Processing:  38%|███▊      | 363/947 [06:50<14:05,  1.45s/it]

Saved batch 63 to ../../data/curation_v1/perturbations/cmpds_names/batch_0063.json

Processing:  38%|███▊      | 364/947 [06:52<13:45,  1.42s/it]

Saved batch 138 to ../../data/curation_v1/perturbations/cmpds_names/batch_0138.json

Processing:  39%|███▊      | 365/947 [06:54<15:09,  1.56s/it]

Saved batch 528 to ../../data/curation_v1/perturbations/cmpds_names/batch_0528.json

Processing:  39%|███▊      | 366/947 [06:55<13:44,  1.42s/it]

Saved batch 683 to ../../data/curation_v1/perturbations/cmpds_names/batch_0683.json

Processing:  39%|███▉      | 367/947 [06:56<14:14,  1.47s/it]

Saved batch 684 to ../../data/curation_v1/perturbations/cmpds_names/batch_0684.json

Processing:  39%|███▉      | 368/947 [06:57<11:45,  1.22s/it]

Saved batch 62 to ../../data/curation_v1/perturbations/cmpds_names/batch_0062.json

Processing:  39%|███▉      | 369/947 [06:59<14:39,  1.52s/it]

Saved batch 918 to ../../data/curation_v1/perturbations/cmpds_names/batch_0918.json
Saved batch 139 to ../../data/curation_v1/perturbations/cmpds_names/batch_0139.json

Processing:  39%|███▉      | 371/947 [07:00<09:17,  1.03it/s]

Saved batch 840 to ../../data/curation_v1/perturbations/cmpds_names/batch_0840.json
Saved batch 839 to ../../data/curation_v1/perturbations/cmpds_names/batch_0839.json

Processing:  39%|███▉      | 373/947 [07:01<07:51,  1.22it/s]

Saved batch 294 to ../../data/curation_v1/perturbations/cmpds_names/batch_0294.json

Processing:  39%|███▉      | 374/947 [07:02<07:55,  1.21it/s]

Saved batch 529 to ../../data/curation_v1/perturbations/cmpds_names/batch_0529.json

Processing:  40%|███▉      | 375/947 [07:03<07:47,  1.22it/s]

Saved batch 295 to ../../data/curation_v1/perturbations/cmpds_names/batch_0295.json

Processing:  40%|███▉      | 376/947 [07:07<15:35,  1.64s/it]

Saved batch 61 to ../../data/curation_v1/perturbations/cmpds_names/batch_0061.json

Processing:  40%|███▉      | 377/947 [07:07<13:34,  1.43s/it]

Saved batch 919 to ../../data/curation_v1/perturbations/cmpds_names/batch_0919.json

Processing:  40%|███▉      | 378/947 [07:09<13:28,  1.42s/it]

Saved batch 686 to ../../data/curation_v1/perturbations/cmpds_names/batch_0686.json

Processing:  40%|████      | 380/947 [07:09<07:55,  1.19it/s]

Saved batch 841 to ../../data/curation_v1/perturbations/cmpds_names/batch_0841.json
Saved batch 530 to ../../data/curation_v1/perturbations/cmpds_names/batch_0530.json

Processing:  40%|████      | 382/947 [07:11<07:17,  1.29it/s]

Saved batch 296 to ../../data/curation_v1/perturbations/cmpds_names/batch_0296.json
Saved batch 140 to ../../data/curation_v1/perturbations/cmpds_names/batch_0140.json

Processing:  40%|████      | 383/947 [07:12<06:46,  1.39it/s]

Saved batch 685 to ../../data/curation_v1/perturbations/cmpds_names/batch_0685.json

Processing:  41%|████      | 384/947 [07:14<10:45,  1.15s/it]

Saved batch 920 to ../../data/curation_v1/perturbations/cmpds_names/batch_0920.json

Processing:  41%|████      | 385/947 [07:16<12:20,  1.32s/it]

Saved batch 842 to ../../data/curation_v1/perturbations/cmpds_names/batch_0842.json

Processing:  41%|████      | 386/947 [07:16<10:57,  1.17s/it]

Saved batch 141 to ../../data/curation_v1/perturbations/cmpds_names/batch_0141.json

Processing:  41%|████      | 387/947 [07:17<09:40,  1.04s/it]

Saved batch 687 to ../../data/curation_v1/perturbations/cmpds_names/batch_0687.json

Processing:  41%|████      | 388/947 [07:18<09:56,  1.07s/it]

Saved batch 531 to ../../data/curation_v1/perturbations/cmpds_names/batch_0531.json

Processing:  41%|████      | 389/947 [07:18<07:44,  1.20it/s]

Saved batch 297 to ../../data/curation_v1/perturbations/cmpds_names/batch_0297.json

Processing:  41%|████      | 390/947 [07:22<15:40,  1.69s/it]

Saved batch 843 to ../../data/curation_v1/perturbations/cmpds_names/batch_0843.json

Processing:  41%|████▏     | 391/947 [07:22<11:45,  1.27s/it]

Saved batch 298 to ../../data/curation_v1/perturbations/cmpds_names/batch_0298.json

Processing:  41%|████▏     | 392/947 [07:23<09:08,  1.01it/s]

Saved batch 60 to ../../data/curation_v1/perturbations/cmpds_names/batch_0060.json

Processing:  41%|████▏     | 393/947 [07:24<08:52,  1.04it/s]

Saved batch 68 to ../../data/curation_v1/perturbations/cmpds_names/batch_0068.json

Processing:  42%|████▏     | 394/947 [07:25<08:43,  1.06it/s]

Saved batch 921 to ../../data/curation_v1/perturbations/cmpds_names/batch_0921.json

Processing:  42%|████▏     | 395/947 [07:27<12:52,  1.40s/it]

Saved batch 688 to ../../data/curation_v1/perturbations/cmpds_names/batch_0688.json

Processing:  42%|████▏     | 396/947 [07:28<12:53,  1.40s/it]

Saved batch 532 to ../../data/curation_v1/perturbations/cmpds_names/batch_0532.json

Processing:  42%|████▏     | 397/947 [07:29<11:08,  1.22s/it]

Saved batch 142 to ../../data/curation_v1/perturbations/cmpds_names/batch_0142.json

Processing:  42%|████▏     | 398/947 [07:31<12:57,  1.42s/it]

Saved batch 299 to ../../data/curation_v1/perturbations/cmpds_names/batch_0299.json

Processing:  42%|████▏     | 399/947 [07:32<11:02,  1.21s/it]

Saved batch 922 to ../../data/curation_v1/perturbations/cmpds_names/batch_0922.json

Processing:  42%|████▏     | 400/947 [07:32<08:21,  1.09it/s]

Saved batch 844 to ../../data/curation_v1/perturbations/cmpds_names/batch_0844.json

Processing:  42%|████▏     | 401/947 [07:33<07:36,  1.20it/s]

Saved batch 689 to ../../data/curation_v1/perturbations/cmpds_names/batch_0689.json

Processing:  42%|████▏     | 402/947 [07:34<08:04,  1.12it/s]

Saved batch 143 to ../../data/curation_v1/perturbations/cmpds_names/batch_0143.json

Processing:  43%|████▎     | 403/947 [07:36<10:56,  1.21s/it]

Saved batch 65 to ../../data/curation_v1/perturbations/cmpds_names/batch_0065.json

Processing:  43%|████▎     | 404/947 [07:36<08:57,  1.01it/s]

Saved batch 67 to ../../data/curation_v1/perturbations/cmpds_names/batch_0067.json

Processing:  43%|████▎     | 405/947 [07:37<07:16,  1.24it/s]

Saved batch 533 to ../../data/curation_v1/perturbations/cmpds_names/batch_0533.json

Processing:  43%|████▎     | 406/947 [07:39<11:54,  1.32s/it]

Saved batch 144 to ../../data/curation_v1/perturbations/cmpds_names/batch_0144.json

Processing:  43%|████▎     | 408/947 [07:40<08:24,  1.07it/s]

Saved batch 534 to ../../data/curation_v1/perturbations/cmpds_names/batch_0534.json
Saved batch 300 to ../../data/curation_v1/perturbations/cmpds_names/batch_0300.json

Processing:  43%|████▎     | 409/947 [07:41<07:06,  1.26it/s]

Saved batch 690 to ../../data/curation_v1/perturbations/cmpds_names/batch_0690.json

Processing:  43%|████▎     | 410/947 [07:44<14:05,  1.57s/it]

Saved batch 66 to ../../data/curation_v1/perturbations/cmpds_names/batch_0066.json

Processing:  43%|████▎     | 411/947 [07:45<10:32,  1.18s/it]

Saved batch 923 to ../../data/curation_v1/perturbations/cmpds_names/batch_0923.json

Processing:  44%|████▎     | 413/947 [07:46<08:09,  1.09it/s]

Saved batch 301 to ../../data/curation_v1/perturbations/cmpds_names/batch_0301.json
Saved batch 845 to ../../data/curation_v1/perturbations/cmpds_names/batch_0845.json

Processing:  44%|████▎     | 414/947 [07:48<09:31,  1.07s/it]

Saved batch 847 to ../../data/curation_v1/perturbations/cmpds_names/batch_0847.json

Processing:  44%|████▍     | 416/947 [07:49<06:36,  1.34it/s]

Saved batch 846 to ../../data/curation_v1/perturbations/cmpds_names/batch_0846.json
Saved batch 535 to ../../data/curation_v1/perturbations/cmpds_names/batch_0535.json

Processing:  44%|████▍     | 417/947 [07:49<06:33,  1.35it/s]

Saved batch 145 to ../../data/curation_v1/perturbations/cmpds_names/batch_0145.json

Processing:  44%|████▍     | 418/947 [07:50<06:45,  1.31it/s]

Saved batch 691 to ../../data/curation_v1/perturbations/cmpds_names/batch_0691.json

Processing:  44%|████▍     | 419/947 [07:52<09:02,  1.03s/it]

Saved batch 302 to ../../data/curation_v1/perturbations/cmpds_names/batch_0302.json

Processing:  44%|████▍     | 420/947 [07:56<17:04,  1.94s/it]

Saved batch 64 to ../../data/curation_v1/perturbations/cmpds_names/batch_0064.json

Processing:  44%|████▍     | 421/947 [07:58<16:52,  1.93s/it]

Saved batch 146 to ../../data/curation_v1/perturbations/cmpds_names/batch_0146.json

Processing:  45%|████▍     | 423/947 [07:58<09:04,  1.04s/it]

Saved batch 924 to ../../data/curation_v1/perturbations/cmpds_names/batch_0924.json
Saved batch 848 to ../../data/curation_v1/perturbations/cmpds_names/batch_0848.json

Processing:  45%|████▍     | 424/947 [07:59<09:06,  1.05s/it]

Saved batch 692 to ../../data/curation_v1/perturbations/cmpds_names/batch_0692.json

Processing:  45%|████▍     | 425/947 [08:00<07:47,  1.12it/s]

Saved batch 925 to ../../data/curation_v1/perturbations/cmpds_names/batch_0925.json

Processing:  45%|████▍     | 426/947 [08:00<07:07,  1.22it/s]

Saved batch 58 to ../../data/curation_v1/perturbations/cmpds_names/batch_0058.json

Processing:  45%|████▌     | 427/947 [08:01<06:48,  1.27it/s]

Saved batch 536 to ../../data/curation_v1/perturbations/cmpds_names/batch_0536.json
Saved batch 147 to ../../data/curation_v1/perturbations/cmpds_names/batch_0147.json

Processing:  45%|████▌     | 430/947 [08:03<05:35,  1.54it/s]

Saved batch 926 to ../../data/curation_v1/perturbations/cmpds_names/batch_0926.json
Saved batch 303 to ../../data/curation_v1/perturbations/cmpds_names/batch_0303.json

Processing:  46%|████▌     | 431/947 [08:07<14:18,  1.66s/it]

Saved batch 304 to ../../data/curation_v1/perturbations/cmpds_names/batch_0304.json

Processing:  46%|████▌     | 432/947 [08:08<11:34,  1.35s/it]

Saved batch 537 to ../../data/curation_v1/perturbations/cmpds_names/batch_0537.json

Processing:  46%|████▌     | 433/947 [08:08<09:03,  1.06s/it]

Saved batch 693 to ../../data/curation_v1/perturbations/cmpds_names/batch_0693.json

Processing:  46%|████▌     | 434/947 [08:09<08:56,  1.05s/it]

Saved batch 57 to ../../data/curation_v1/perturbations/cmpds_names/batch_0057.json

Processing:  46%|████▌     | 436/947 [08:10<05:55,  1.44it/s]

Saved batch 538 to ../../data/curation_v1/perturbations/cmpds_names/batch_0538.json
Saved batch 849 to ../../data/curation_v1/perturbations/cmpds_names/batch_0849.json

Processing:  46%|████▌     | 437/947 [08:12<08:19,  1.02it/s]

Saved batch 927 to ../../data/curation_v1/perturbations/cmpds_names/batch_0927.json

Processing:  46%|████▋     | 438/947 [08:14<10:56,  1.29s/it]

Saved batch 149 to ../../data/curation_v1/perturbations/cmpds_names/batch_0149.json

Processing:  46%|████▋     | 439/947 [08:15<10:05,  1.19s/it]

Saved batch 539 to ../../data/curation_v1/perturbations/cmpds_names/batch_0539.json

Processing:  46%|████▋     | 440/947 [08:15<08:08,  1.04it/s]

Saved batch 305 to ../../data/curation_v1/perturbations/cmpds_names/batch_0305.json

Processing:  47%|████▋     | 441/947 [08:16<07:07,  1.18it/s]

Saved batch 850 to ../../data/curation_v1/perturbations/cmpds_names/batch_0850.json

Processing:  47%|████▋     | 442/947 [08:16<05:53,  1.43it/s]

Saved batch 56 to ../../data/curation_v1/perturbations/cmpds_names/batch_0056.json

Processing:  47%|████▋     | 443/947 [08:18<09:28,  1.13s/it]

Saved batch 148 to ../../data/curation_v1/perturbations/cmpds_names/batch_0148.json

Processing:  47%|████▋     | 444/947 [08:19<08:38,  1.03s/it]

Saved batch 928 to ../../data/curation_v1/perturbations/cmpds_names/batch_0928.json

Processing:  47%|████▋     | 445/947 [08:20<08:08,  1.03it/s]

Saved batch 851 to ../../data/curation_v1/perturbations/cmpds_names/batch_0851.json

Processing:  47%|████▋     | 446/947 [08:23<13:26,  1.61s/it]

Saved batch 694 to ../../data/curation_v1/perturbations/cmpds_names/batch_0694.json

Processing:  47%|████▋     | 447/947 [08:23<10:06,  1.21s/it]

Saved batch 306 to ../../data/curation_v1/perturbations/cmpds_names/batch_0306.json

Processing:  47%|████▋     | 448/947 [08:24<08:47,  1.06s/it]

Saved batch 150 to ../../data/curation_v1/perturbations/cmpds_names/batch_0150.json
Saved batch 929 to ../../data/curation_v1/perturbations/cmpds_names/batch_0929.json

Processing:  48%|████▊     | 450/947 [08:25<07:06,  1.17it/s]

Saved batch 696 to ../../data/curation_v1/perturbations/cmpds_names/batch_0696.json

Processing:  48%|████▊     | 451/947 [08:25<06:06,  1.35it/s]

Saved batch 55 to ../../data/curation_v1/perturbations/cmpds_names/batch_0055.json

Processing:  48%|████▊     | 452/947 [08:27<08:37,  1.04s/it]

Saved batch 77 to ../../data/curation_v1/perturbations/cmpds_names/batch_0077.json

Processing:  48%|████▊     | 453/947 [08:29<10:18,  1.25s/it]

Saved batch 852 to ../../data/curation_v1/perturbations/cmpds_names/batch_0852.json

Processing:  48%|████▊     | 454/947 [08:30<08:10,  1.00it/s]

Saved batch 151 to ../../data/curation_v1/perturbations/cmpds_names/batch_0151.json

Processing:  48%|████▊     | 455/947 [08:30<06:18,  1.30it/s]

Saved batch 540 to ../../data/curation_v1/perturbations/cmpds_names/batch_0540.json

Processing:  48%|████▊     | 456/947 [08:32<10:52,  1.33s/it]

Saved batch 307 to ../../data/curation_v1/perturbations/cmpds_names/batch_0307.json
Saved batch 541 to ../../data/curation_v1/perturbations/cmpds_names/batch_0541.json

Processing:  48%|████▊     | 458/947 [08:33<07:28,  1.09it/s]

Saved batch 697 to ../../data/curation_v1/perturbations/cmpds_names/batch_0697.json

Processing:  48%|████▊     | 459/947 [08:38<14:05,  1.73s/it]

Saved batch 930 to ../../data/curation_v1/perturbations/cmpds_names/batch_0930.json

Processing:  49%|████▊     | 460/947 [08:39<13:16,  1.64s/it]

Saved batch 308 to ../../data/curation_v1/perturbations/cmpds_names/batch_0308.json

Processing:  49%|████▊     | 461/947 [08:40<12:25,  1.53s/it]

Saved batch 152 to ../../data/curation_v1/perturbations/cmpds_names/batch_0152.json

Processing:  49%|████▉     | 462/947 [08:41<10:07,  1.25s/it]

Saved batch 76 to ../../data/curation_v1/perturbations/cmpds_names/batch_0076.json

Processing:  49%|████▉     | 463/947 [08:42<10:14,  1.27s/it]

Saved batch 542 to ../../data/curation_v1/perturbations/cmpds_names/batch_0542.json

Processing:  49%|████▉     | 464/947 [08:47<18:40,  2.32s/it]

Saved batch 931 to ../../data/curation_v1/perturbations/cmpds_names/batch_0931.json
Saved batch 698 to ../../data/curation_v1/perturbations/cmpds_names/batch_0698.json

Processing:  49%|████▉     | 466/947 [08:47<11:18,  1.41s/it]

Saved batch 695 to ../../data/curation_v1/perturbations/cmpds_names/batch_0695.json

Processing:  49%|████▉     | 467/947 [08:48<09:03,  1.13s/it]

Saved batch 153 to ../../data/curation_v1/perturbations/cmpds_names/batch_0153.json

Processing:  49%|████▉     | 468/947 [08:49<09:52,  1.24s/it]

Saved batch 75 to ../../data/curation_v1/perturbations/cmpds_names/batch_0075.json

Processing:  50%|████▉     | 469/947 [08:54<16:32,  2.08s/it]

Saved batch 543 to ../../data/curation_v1/perturbations/cmpds_names/batch_0543.json

Processing:  50%|████▉     | 470/947 [08:54<12:34,  1.58s/it]

Saved batch 855 to ../../data/curation_v1/perturbations/cmpds_names/batch_0855.json

Processing:  50%|████▉     | 471/947 [08:57<15:00,  1.89s/it]

Saved batch 699 to ../../data/curation_v1/perturbations/cmpds_names/batch_0699.json

Processing:  50%|████▉     | 472/947 [08:57<11:14,  1.42s/it]

Saved batch 80 to ../../data/curation_v1/perturbations/cmpds_names/batch_0080.json

Processing:  50%|████▉     | 473/947 [08:58<10:09,  1.28s/it]

Saved batch 854 to ../../data/curation_v1/perturbations/cmpds_names/batch_0854.json

Processing:  50%|█████     | 474/947 [09:01<14:45,  1.87s/it]

Saved batch 309 to ../../data/curation_v1/perturbations/cmpds_names/batch_0309.json

Processing:  50%|█████     | 476/947 [09:03<09:41,  1.24s/it]

Saved batch 310 to ../../data/curation_v1/perturbations/cmpds_names/batch_0310.json
Saved batch 932 to ../../data/curation_v1/perturbations/cmpds_names/batch_0932.json

Processing:  50%|█████     | 477/947 [09:03<07:14,  1.08it/s]

Saved batch 856 to ../../data/curation_v1/perturbations/cmpds_names/batch_0856.json

Processing:  50%|█████     | 478/947 [09:06<12:10,  1.56s/it]

Saved batch 700 to ../../data/curation_v1/perturbations/cmpds_names/batch_0700.json

Processing:  51%|█████     | 479/947 [09:08<13:55,  1.78s/it]

Saved batch 154 to ../../data/curation_v1/perturbations/cmpds_names/batch_0154.json

Processing:  51%|█████     | 480/947 [09:09<12:58,  1.67s/it]

Saved batch 701 to ../../data/curation_v1/perturbations/cmpds_names/batch_0701.json

Processing:  51%|█████     | 481/947 [09:11<13:09,  1.69s/it]

Saved batch 857 to ../../data/curation_v1/perturbations/cmpds_names/batch_0857.json

Processing:  51%|█████     | 482/947 [09:14<14:36,  1.88s/it]

Saved batch 155 to ../../data/curation_v1/perturbations/cmpds_names/batch_0155.json

Processing:  51%|█████     | 483/947 [09:14<11:27,  1.48s/it]

Saved batch 933 to ../../data/curation_v1/perturbations/cmpds_names/batch_0933.json

Processing:  51%|█████     | 484/947 [09:16<12:44,  1.65s/it]

Saved batch 311 to ../../data/curation_v1/perturbations/cmpds_names/batch_0311.json

Processing:  51%|█████     | 485/947 [09:17<11:28,  1.49s/it]

Saved batch 545 to ../../data/curation_v1/perturbations/cmpds_names/batch_0545.json

Processing:  51%|█████▏    | 486/947 [09:20<14:48,  1.93s/it]

Saved batch 702 to ../../data/curation_v1/perturbations/cmpds_names/batch_0702.json

Processing:  51%|█████▏    | 487/947 [09:21<12:19,  1.61s/it]

Saved batch 935 to ../../data/curation_v1/perturbations/cmpds_names/batch_0935.json

Processing:  52%|█████▏    | 488/947 [09:22<11:41,  1.53s/it]

Saved batch 858 to ../../data/curation_v1/perturbations/cmpds_names/batch_0858.json

Processing:  52%|█████▏    | 489/947 [09:23<09:08,  1.20s/it]

Saved batch 156 to ../../data/curation_v1/perturbations/cmpds_names/batch_0156.json

Processing:  52%|█████▏    | 490/947 [09:23<07:01,  1.08it/s]

Saved batch 546 to ../../data/curation_v1/perturbations/cmpds_names/batch_0546.json

Processing:  52%|█████▏    | 492/947 [09:28<11:22,  1.50s/it]

Saved batch 157 to ../../data/curation_v1/perturbations/cmpds_names/batch_0157.json
Saved batch 544 to ../../data/curation_v1/perturbations/cmpds_names/batch_0544.json

Processing:  52%|█████▏    | 493/947 [09:29<10:47,  1.43s/it]

Saved batch 934 to ../../data/curation_v1/perturbations/cmpds_names/batch_0934.json

Processing:  52%|█████▏    | 495/947 [09:30<07:12,  1.04it/s]

Saved batch 936 to ../../data/curation_v1/perturbations/cmpds_names/batch_0936.json
Saved batch 313 to ../../data/curation_v1/perturbations/cmpds_names/batch_0313.json

Processing:  52%|█████▏    | 496/947 [09:31<06:06,  1.23it/s]

Saved batch 703 to ../../data/curation_v1/perturbations/cmpds_names/batch_0703.json

Processing:  52%|█████▏    | 497/947 [09:34<12:02,  1.60s/it]

Saved batch 547 to ../../data/curation_v1/perturbations/cmpds_names/batch_0547.json

Processing:  53%|█████▎    | 498/947 [09:36<12:49,  1.71s/it]

Saved batch 79 to ../../data/curation_v1/perturbations/cmpds_names/batch_0079.json

Processing:  53%|█████▎    | 499/947 [09:38<11:59,  1.61s/it]

Saved batch 78 to ../../data/curation_v1/perturbations/cmpds_names/batch_0078.json

Processing:  53%|█████▎    | 500/947 [09:38<09:12,  1.24s/it]

Saved batch 314 to ../../data/curation_v1/perturbations/cmpds_names/batch_0314.json

Processing:  53%|█████▎    | 501/947 [09:39<09:11,  1.24s/it]

Saved batch 937 to ../../data/curation_v1/perturbations/cmpds_names/batch_0937.json

Processing:  53%|█████▎    | 502/947 [09:48<25:40,  3.46s/it]

Saved batch 81 to ../../data/curation_v1/perturbations/cmpds_names/batch_0081.json

Processing:  53%|█████▎    | 503/947 [09:49<20:14,  2.73s/it]

Saved batch 704 to ../../data/curation_v1/perturbations/cmpds_names/batch_0704.json

Processing:  53%|█████▎    | 504/947 [09:50<16:15,  2.20s/it]

Saved batch 938 to ../../data/curation_v1/perturbations/cmpds_names/batch_0938.json

Processing:  53%|█████▎    | 505/947 [09:53<17:59,  2.44s/it]

Saved batch 312 to ../../data/curation_v1/perturbations/cmpds_names/batch_0312.json

Processing:  53%|█████▎    | 506/947 [09:53<13:20,  1.82s/it]

Saved batch 859 to ../../data/curation_v1/perturbations/cmpds_names/batch_0859.json

Processing:  54%|█████▎    | 507/947 [09:55<13:53,  1.89s/it]

Saved batch 158 to ../../data/curation_v1/perturbations/cmpds_names/batch_0158.json

Processing:  54%|█████▎    | 508/947 [09:56<10:19,  1.41s/it]

Saved batch 860 to ../../data/curation_v1/perturbations/cmpds_names/batch_0860.json

Processing:  54%|█████▎    | 509/947 [09:56<08:01,  1.10s/it]

Saved batch 159 to ../../data/curation_v1/perturbations/cmpds_names/batch_0159.json

Processing:  54%|█████▍    | 510/947 [09:56<06:28,  1.12it/s]

Saved batch 549 to ../../data/curation_v1/perturbations/cmpds_names/batch_0549.json

Processing:  54%|█████▍    | 511/947 [09:57<06:23,  1.14it/s]

Saved batch 548 to ../../data/curation_v1/perturbations/cmpds_names/batch_0548.json

Processing:  54%|█████▍    | 512/947 [10:00<09:14,  1.27s/it]

Saved batch 315 to ../../data/curation_v1/perturbations/cmpds_names/batch_0315.json

Processing:  54%|█████▍    | 513/947 [10:01<09:10,  1.27s/it]

Saved batch 939 to ../../data/curation_v1/perturbations/cmpds_names/batch_0939.json

Processing:  54%|█████▍    | 515/947 [10:02<05:50,  1.23it/s]

Saved batch 705 to ../../data/curation_v1/perturbations/cmpds_names/batch_0705.json
Saved batch 82 to ../../data/curation_v1/perturbations/cmpds_names/batch_0082.json

Processing:  54%|█████▍    | 516/947 [10:02<05:33,  1.29it/s]

Saved batch 861 to ../../data/curation_v1/perturbations/cmpds_names/batch_0861.json

Processing:  55%|█████▍    | 517/947 [10:05<08:42,  1.22s/it]

Saved batch 316 to ../../data/curation_v1/perturbations/cmpds_names/batch_0316.json

Processing:  55%|█████▍    | 518/947 [10:05<06:46,  1.05it/s]

Saved batch 706 to ../../data/curation_v1/perturbations/cmpds_names/batch_0706.json

Processing:  55%|█████▍    | 520/947 [10:08<07:53,  1.11s/it]

Saved batch 940 to ../../data/curation_v1/perturbations/cmpds_names/batch_0940.json
Saved batch 160 to ../../data/curation_v1/perturbations/cmpds_names/batch_0160.json
Saved batch 317 to ../../data/curation_v1/perturbations/cmpds_names/batch_0317.json

Processing:  55%|█████▌    | 522/947 [10:11<09:50,  1.39s/it]

Saved batch 83 to ../../data/curation_v1/perturbations/cmpds_names/batch_0083.json

Processing:  55%|█████▌    | 523/947 [10:12<09:19,  1.32s/it]

Saved batch 551 to ../../data/curation_v1/perturbations/cmpds_names/batch_0551.json

Processing:  55%|█████▌    | 524/947 [10:16<13:01,  1.85s/it]

Saved batch 862 to ../../data/curation_v1/perturbations/cmpds_names/batch_0862.json

Processing:  55%|█████▌    | 525/947 [10:17<10:59,  1.56s/it]

Saved batch 707 to ../../data/curation_v1/perturbations/cmpds_names/batch_0707.json
Saved batch 550 to ../../data/curation_v1/perturbations/cmpds_names/batch_0550.json

Processing:  56%|█████▌    | 527/947 [10:17<07:28,  1.07s/it]

Saved batch 941 to ../../data/curation_v1/perturbations/cmpds_names/batch_0941.json

Processing:  56%|█████▌    | 528/947 [10:18<07:15,  1.04s/it]

Saved batch 318 to ../../data/curation_v1/perturbations/cmpds_names/batch_0318.json

Processing:  56%|█████▌    | 529/947 [10:22<11:56,  1.72s/it]

Saved batch 161 to ../../data/curation_v1/perturbations/cmpds_names/batch_0161.json

Processing:  56%|█████▌    | 530/947 [10:27<16:57,  2.44s/it]

Saved batch 552 to ../../data/curation_v1/perturbations/cmpds_names/batch_0552.json
Saved batch 84 to ../../data/curation_v1/perturbations/cmpds_names/batch_0084.json

Processing:  56%|█████▌    | 532/947 [10:27<10:18,  1.49s/it]

Saved batch 942 to ../../data/curation_v1/perturbations/cmpds_names/batch_0942.json

Processing:  56%|█████▋    | 533/947 [10:29<11:48,  1.71s/it]

Saved batch 864 to ../../data/curation_v1/perturbations/cmpds_names/batch_0864.json

Processing:  56%|█████▋    | 535/947 [10:32<09:53,  1.44s/it]

Saved batch 85 to ../../data/curation_v1/perturbations/cmpds_names/batch_0085.json
Saved batch 163 to ../../data/curation_v1/perturbations/cmpds_names/batch_0163.json

Processing:  57%|█████▋    | 536/947 [10:34<10:02,  1.47s/it]

Saved batch 162 to ../../data/curation_v1/perturbations/cmpds_names/batch_0162.json

Processing:  57%|█████▋    | 537/947 [10:34<07:43,  1.13s/it]

Saved batch 708 to ../../data/curation_v1/perturbations/cmpds_names/batch_0708.json

Processing:  57%|█████▋    | 538/947 [10:35<07:20,  1.08s/it]

Saved batch 553 to ../../data/curation_v1/perturbations/cmpds_names/batch_0553.json

Processing:  57%|█████▋    | 539/947 [10:35<05:58,  1.14it/s]

Saved batch 863 to ../../data/curation_v1/perturbations/cmpds_names/batch_0863.json

Processing:  57%|█████▋    | 540/947 [10:36<05:01,  1.35it/s]

Saved batch 319 to ../../data/curation_v1/perturbations/cmpds_names/batch_0319.json

Processing:  57%|█████▋    | 541/947 [10:36<04:22,  1.54it/s]

Saved batch 709 to ../../data/curation_v1/perturbations/cmpds_names/batch_0709.json

Processing:  57%|█████▋    | 542/947 [10:38<07:15,  1.08s/it]

Saved batch 865 to ../../data/curation_v1/perturbations/cmpds_names/batch_0865.json

Processing:  57%|█████▋    | 543/947 [10:41<10:25,  1.55s/it]

Saved batch 320 to ../../data/curation_v1/perturbations/cmpds_names/batch_0320.json
Saved batch 164 to ../../data/curation_v1/perturbations/cmpds_names/batch_0164.json

Processing:  58%|█████▊    | 546/947 [10:44<07:52,  1.18s/it]

Saved batch 943 to ../../data/curation_v1/perturbations/cmpds_names/batch_0943.json
Saved batch 554 to ../../data/curation_v1/perturbations/cmpds_names/batch_0554.json

Processing:  58%|█████▊    | 547/947 [10:45<07:35,  1.14s/it]

Saved batch 710 to ../../data/curation_v1/perturbations/cmpds_names/batch_0710.json

Processing:  58%|█████▊    | 548/947 [10:45<06:22,  1.04it/s]

Saved batch 5 to ../../data/curation_v1/perturbations/cmpds_names/batch_0005.json

Processing:  58%|█████▊    | 549/947 [10:46<05:18,  1.25it/s]

Saved batch 398 to ../../data/curation_v1/perturbations/cmpds_names/batch_0398.json

Processing:  58%|█████▊    | 550/947 [10:47<05:23,  1.23it/s]

Saved batch 944 to ../../data/curation_v1/perturbations/cmpds_names/batch_0944.json

Processing:  58%|█████▊    | 551/947 [10:49<07:24,  1.12s/it]

Saved batch 165 to ../../data/curation_v1/perturbations/cmpds_names/batch_0165.json

Processing:  58%|█████▊    | 552/947 [10:50<08:18,  1.26s/it]

Saved batch 321 to ../../data/curation_v1/perturbations/cmpds_names/batch_0321.json

Processing:  58%|█████▊    | 553/947 [10:51<08:15,  1.26s/it]

Saved batch 711 to ../../data/curation_v1/perturbations/cmpds_names/batch_0711.json

Processing:  59%|█████▊    | 554/947 [10:54<11:33,  1.76s/it]

Saved batch 555 to ../../data/curation_v1/perturbations/cmpds_names/batch_0555.json

Processing:  59%|█████▊    | 555/947 [10:56<10:22,  1.59s/it]

Saved batch 712 to ../../data/curation_v1/perturbations/cmpds_names/batch_0712.json

Processing:  59%|█████▊    | 556/947 [10:56<08:15,  1.27s/it]

Saved batch 399 to ../../data/curation_v1/perturbations/cmpds_names/batch_0399.json

Processing:  59%|█████▉    | 557/947 [10:56<06:19,  1.03it/s]

Saved batch 556 to ../../data/curation_v1/perturbations/cmpds_names/batch_0556.json

Processing:  59%|█████▉    | 558/947 [10:59<09:00,  1.39s/it]

Saved batch 946 to ../../data/curation_v1/perturbations/cmpds_names/batch_0946.json

Processing:  59%|█████▉    | 559/947 [10:59<07:23,  1.14s/it]

Saved batch 166 to ../../data/curation_v1/perturbations/cmpds_names/batch_0166.json

Processing:  59%|█████▉    | 560/947 [11:00<06:56,  1.08s/it]

Saved batch 400 to ../../data/curation_v1/perturbations/cmpds_names/batch_0400.json

Processing:  59%|█████▉    | 561/947 [11:01<06:07,  1.05it/s]

Saved batch 945 to ../../data/curation_v1/perturbations/cmpds_names/batch_0945.json

Processing:  60%|█████▉    | 564/947 [11:06<07:14,  1.13s/it]

Saved batch 323 to ../../data/curation_v1/perturbations/cmpds_names/batch_0323.json
Saved batch 324 to ../../data/curation_v1/perturbations/cmpds_names/batch_0324.json
Saved batch 401 to ../../data/curation_v1/perturbations/cmpds_names/batch_0401.json

Processing:  60%|█████▉    | 565/947 [11:06<06:34,  1.03s/it]

Saved batch 402 to ../../data/curation_v1/perturbations/cmpds_names/batch_0402.json
Saved batch 713 to ../../data/curation_v1/perturbations/cmpds_names/batch_0713.json

Processing:  60%|█████▉    | 567/947 [11:08<05:57,  1.06it/s]

Saved batch 167 to ../../data/curation_v1/perturbations/cmpds_names/batch_0167.json

Processing:  60%|█████▉    | 568/947 [11:15<14:08,  2.24s/it]

Saved batch 325 to ../../data/curation_v1/perturbations/cmpds_names/batch_0325.json

Processing:  60%|██████    | 570/947 [11:15<08:47,  1.40s/it]

Saved batch 557 to ../../data/curation_v1/perturbations/cmpds_names/batch_0557.json
Saved batch 168 to ../../data/curation_v1/perturbations/cmpds_names/batch_0168.json

Processing:  60%|██████    | 571/947 [11:16<08:04,  1.29s/it]

Saved batch 403 to ../../data/curation_v1/perturbations/cmpds_names/batch_0403.json

Processing:  60%|██████    | 572/947 [11:17<07:35,  1.21s/it]

Saved batch 714 to ../../data/curation_v1/perturbations/cmpds_names/batch_0714.json

Processing:  61%|██████    | 573/947 [11:18<06:56,  1.11s/it]

Saved batch 559 to ../../data/curation_v1/perturbations/cmpds_names/batch_0559.json

Processing:  61%|██████    | 574/947 [11:19<05:50,  1.06it/s]

Saved batch 322 to ../../data/curation_v1/perturbations/cmpds_names/batch_0322.json

Processing:  61%|██████    | 575/947 [11:20<06:41,  1.08s/it]

Saved batch 326 to ../../data/curation_v1/perturbations/cmpds_names/batch_0326.json

Processing:  61%|██████    | 576/947 [11:21<05:31,  1.12it/s]

Saved batch 169 to ../../data/curation_v1/perturbations/cmpds_names/batch_0169.json

Processing:  61%|██████    | 577/947 [11:21<05:19,  1.16it/s]

Saved batch 558 to ../../data/curation_v1/perturbations/cmpds_names/batch_0558.json

Processing:  61%|██████    | 578/947 [11:27<13:52,  2.26s/it]

Saved batch 716 to ../../data/curation_v1/perturbations/cmpds_names/batch_0716.json

Processing:  61%|██████    | 580/947 [11:28<08:08,  1.33s/it]

Saved batch 404 to ../../data/curation_v1/perturbations/cmpds_names/batch_0404.json
Saved batch 560 to ../../data/curation_v1/perturbations/cmpds_names/batch_0560.json

Processing:  61%|██████▏   | 581/947 [11:29<06:56,  1.14s/it]

Saved batch 327 to ../../data/curation_v1/perturbations/cmpds_names/batch_0327.json

Processing:  61%|██████▏   | 582/947 [11:31<09:51,  1.62s/it]

Saved batch 171 to ../../data/curation_v1/perturbations/cmpds_names/batch_0171.json

Processing:  62%|██████▏   | 583/947 [11:32<08:40,  1.43s/it]

Saved batch 561 to ../../data/curation_v1/perturbations/cmpds_names/batch_0561.json

Processing:  62%|██████▏   | 584/947 [11:34<09:34,  1.58s/it]

Saved batch 715 to ../../data/curation_v1/perturbations/cmpds_names/batch_0715.json

Processing:  62%|██████▏   | 585/947 [11:35<08:37,  1.43s/it]

Saved batch 328 to ../../data/curation_v1/perturbations/cmpds_names/batch_0328.json

Processing:  62%|██████▏   | 586/947 [11:37<08:49,  1.47s/it]

Saved batch 717 to ../../data/curation_v1/perturbations/cmpds_names/batch_0717.json

Processing:  62%|██████▏   | 587/947 [11:37<07:09,  1.19s/it]

Saved batch 170 to ../../data/curation_v1/perturbations/cmpds_names/batch_0170.json

Processing:  62%|██████▏   | 588/947 [11:38<06:12,  1.04s/it]

Saved batch 405 to ../../data/curation_v1/perturbations/cmpds_names/batch_0405.json

Processing:  62%|██████▏   | 589/947 [11:41<08:54,  1.49s/it]

Saved batch 406 to ../../data/curation_v1/perturbations/cmpds_names/batch_0406.json

Processing:  62%|██████▏   | 591/947 [11:42<06:16,  1.06s/it]

Saved batch 329 to ../../data/curation_v1/perturbations/cmpds_names/batch_0329.json
Saved batch 407 to ../../data/curation_v1/perturbations/cmpds_names/batch_0407.json

Processing:  63%|██████▎   | 592/947 [11:43<05:40,  1.04it/s]

Saved batch 173 to ../../data/curation_v1/perturbations/cmpds_names/batch_0173.json

Processing:  63%|██████▎   | 593/947 [11:43<04:38,  1.27it/s]

Saved batch 718 to ../../data/curation_v1/perturbations/cmpds_names/batch_0718.json

Processing:  63%|██████▎   | 594/947 [11:47<09:39,  1.64s/it]

Saved batch 172 to ../../data/curation_v1/perturbations/cmpds_names/batch_0172.json

Processing:  63%|██████▎   | 595/947 [11:47<07:44,  1.32s/it]

Saved batch 330 to ../../data/curation_v1/perturbations/cmpds_names/batch_0330.json

Processing:  63%|██████▎   | 596/947 [11:48<05:57,  1.02s/it]

Saved batch 563 to ../../data/curation_v1/perturbations/cmpds_names/batch_0563.json

Processing:  63%|██████▎   | 597/947 [11:50<07:19,  1.26s/it]

Saved batch 562 to ../../data/curation_v1/perturbations/cmpds_names/batch_0562.json

Processing:  63%|██████▎   | 598/947 [11:50<05:58,  1.03s/it]

Saved batch 720 to ../../data/curation_v1/perturbations/cmpds_names/batch_0720.json

Processing:  63%|██████▎   | 599/947 [11:52<08:22,  1.44s/it]

Saved batch 408 to ../../data/curation_v1/perturbations/cmpds_names/batch_0408.json

Processing:  63%|██████▎   | 600/947 [11:53<06:21,  1.10s/it]

Saved batch 719 to ../../data/curation_v1/perturbations/cmpds_names/batch_0719.json

Processing:  63%|██████▎   | 601/947 [11:53<04:57,  1.16it/s]

Saved batch 564 to ../../data/curation_v1/perturbations/cmpds_names/batch_0564.json

Processing:  64%|██████▎   | 602/947 [11:53<04:09,  1.38it/s]

Saved batch 174 to ../../data/curation_v1/perturbations/cmpds_names/batch_0174.json

Processing:  64%|██████▎   | 603/947 [11:54<03:50,  1.49it/s]

Saved batch 331 to ../../data/curation_v1/perturbations/cmpds_names/batch_0331.json

Processing:  64%|██████▍   | 604/947 [11:55<04:48,  1.19it/s]

Saved batch 409 to ../../data/curation_v1/perturbations/cmpds_names/batch_0409.json

Processing:  64%|██████▍   | 605/947 [11:59<09:06,  1.60s/it]

Saved batch 176 to ../../data/curation_v1/perturbations/cmpds_names/batch_0176.json

Processing:  64%|██████▍   | 607/947 [11:59<05:07,  1.11it/s]

Saved batch 175 to ../../data/curation_v1/perturbations/cmpds_names/batch_0175.json
Saved batch 721 to ../../data/curation_v1/perturbations/cmpds_names/batch_0721.json

Processing:  64%|██████▍   | 608/947 [12:01<06:25,  1.14s/it]

Saved batch 332 to ../../data/curation_v1/perturbations/cmpds_names/batch_0332.json

Processing:  64%|██████▍   | 609/947 [12:02<05:41,  1.01s/it]

Saved batch 565 to ../../data/curation_v1/perturbations/cmpds_names/batch_0565.json

Processing:  64%|██████▍   | 610/947 [12:02<05:00,  1.12it/s]

Saved batch 722 to ../../data/curation_v1/perturbations/cmpds_names/batch_0722.json

Processing:  65%|██████▍   | 611/947 [12:02<03:58,  1.41it/s]

Saved batch 410 to ../../data/curation_v1/perturbations/cmpds_names/batch_0410.json

Processing:  65%|██████▍   | 612/947 [12:06<08:32,  1.53s/it]

Saved batch 333 to ../../data/curation_v1/perturbations/cmpds_names/batch_0333.json

Processing:  65%|██████▍   | 613/947 [12:08<08:51,  1.59s/it]

Saved batch 177 to ../../data/curation_v1/perturbations/cmpds_names/batch_0177.json

Processing:  65%|██████▍   | 614/947 [12:11<12:05,  2.18s/it]

Saved batch 178 to ../../data/curation_v1/perturbations/cmpds_names/batch_0178.json

Processing:  65%|██████▍   | 615/947 [12:12<09:14,  1.67s/it]

Saved batch 412 to ../../data/curation_v1/perturbations/cmpds_names/batch_0412.json

Processing:  65%|██████▌   | 616/947 [12:12<07:06,  1.29s/it]

Saved batch 723 to ../../data/curation_v1/perturbations/cmpds_names/batch_0723.json

Processing:  65%|██████▌   | 618/947 [12:13<04:09,  1.32it/s]

Saved batch 566 to ../../data/curation_v1/perturbations/cmpds_names/batch_0566.json
Saved batch 334 to ../../data/curation_v1/perturbations/cmpds_names/batch_0334.json

Processing:  65%|██████▌   | 619/947 [12:14<04:52,  1.12it/s]

Saved batch 411 to ../../data/curation_v1/perturbations/cmpds_names/batch_0411.json

Processing:  65%|██████▌   | 620/947 [12:17<08:45,  1.61s/it]

Saved batch 567 to ../../data/curation_v1/perturbations/cmpds_names/batch_0567.json

Processing:  66%|██████▌   | 621/947 [12:18<06:48,  1.25s/it]

Saved batch 724 to ../../data/curation_v1/perturbations/cmpds_names/batch_0724.json
Saved batch 179 to ../../data/curation_v1/perturbations/cmpds_names/batch_0179.json

Processing:  66%|██████▌   | 623/947 [12:22<09:19,  1.73s/it]

Saved batch 568 to ../../data/curation_v1/perturbations/cmpds_names/batch_0568.json

Processing:  66%|██████▌   | 624/947 [12:22<07:24,  1.37s/it]

Saved batch 725 to ../../data/curation_v1/perturbations/cmpds_names/batch_0725.json

Processing:  66%|██████▌   | 625/947 [12:23<06:11,  1.15s/it]

Saved batch 335 to ../../data/curation_v1/perturbations/cmpds_names/batch_0335.json
Saved batch 180 to ../../data/curation_v1/perturbations/cmpds_names/batch_0180.json

Processing:  66%|██████▌   | 627/947 [12:25<05:39,  1.06s/it]

Saved batch 413 to ../../data/curation_v1/perturbations/cmpds_names/batch_0413.json

Processing:  66%|██████▋   | 628/947 [12:27<07:36,  1.43s/it]

Saved batch 569 to ../../data/curation_v1/perturbations/cmpds_names/batch_0569.json

Processing:  66%|██████▋   | 629/947 [12:28<06:56,  1.31s/it]

Saved batch 414 to ../../data/curation_v1/perturbations/cmpds_names/batch_0414.json

Processing:  67%|██████▋   | 630/947 [12:31<08:08,  1.54s/it]

Saved batch 336 to ../../data/curation_v1/perturbations/cmpds_names/batch_0336.json

Processing:  67%|██████▋   | 631/947 [12:35<12:14,  2.33s/it]

Saved batch 570 to ../../data/curation_v1/perturbations/cmpds_names/batch_0570.json

Processing:  67%|██████▋   | 633/947 [12:36<07:32,  1.44s/it]

Saved batch 181 to ../../data/curation_v1/perturbations/cmpds_names/batch_0181.json
Saved batch 726 to ../../data/curation_v1/perturbations/cmpds_names/batch_0726.json

Processing:  67%|██████▋   | 634/947 [12:37<06:53,  1.32s/it]

Saved batch 727 to ../../data/curation_v1/perturbations/cmpds_names/batch_0727.json

Processing:  67%|██████▋   | 635/947 [12:40<09:10,  1.76s/it]

Saved batch 182 to ../../data/curation_v1/perturbations/cmpds_names/batch_0182.json

Processing:  67%|██████▋   | 636/947 [12:45<14:36,  2.82s/it]

Saved batch 416 to ../../data/curation_v1/perturbations/cmpds_names/batch_0416.json
Saved batch 572 to ../../data/curation_v1/perturbations/cmpds_names/batch_0572.json

Processing:  67%|██████▋   | 638/947 [12:49<11:38,  2.26s/it]

Saved batch 728 to ../../data/curation_v1/perturbations/cmpds_names/batch_0728.json

Processing:  67%|██████▋   | 639/947 [12:49<09:30,  1.85s/it]

Saved batch 339 to ../../data/curation_v1/perturbations/cmpds_names/batch_0339.json

Processing:  68%|██████▊   | 640/947 [12:50<07:46,  1.52s/it]

Saved batch 337 to ../../data/curation_v1/perturbations/cmpds_names/batch_0337.json

Processing:  68%|██████▊   | 641/947 [12:53<09:47,  1.92s/it]

Saved batch 415 to ../../data/curation_v1/perturbations/cmpds_names/batch_0415.json

Processing:  68%|██████▊   | 642/947 [12:56<11:33,  2.27s/it]

Saved batch 571 to ../../data/curation_v1/perturbations/cmpds_names/batch_0571.json

Processing:  68%|██████▊   | 643/947 [12:57<09:48,  1.94s/it]

Saved batch 338 to ../../data/curation_v1/perturbations/cmpds_names/batch_0338.json

Processing:  68%|██████▊   | 644/947 [12:58<08:13,  1.63s/it]

Saved batch 183 to ../../data/curation_v1/perturbations/cmpds_names/batch_0183.json

Processing:  68%|██████▊   | 645/947 [12:59<08:08,  1.62s/it]

Saved batch 573 to ../../data/curation_v1/perturbations/cmpds_names/batch_0573.json
Saved batch 340 to ../../data/curation_v1/perturbations/cmpds_names/batch_0340.json

Processing:  68%|██████▊   | 647/947 [13:00<04:56,  1.01it/s]

Saved batch 184 to ../../data/curation_v1/perturbations/cmpds_names/batch_0184.json

Processing:  68%|██████▊   | 648/947 [13:02<06:32,  1.31s/it]

Saved batch 418 to ../../data/curation_v1/perturbations/cmpds_names/batch_0418.json

Processing:  69%|██████▊   | 649/947 [13:03<05:09,  1.04s/it]

Saved batch 417 to ../../data/curation_v1/perturbations/cmpds_names/batch_0417.json

Processing:  69%|██████▊   | 650/947 [13:04<05:28,  1.11s/it]

Saved batch 729 to ../../data/curation_v1/perturbations/cmpds_names/batch_0729.json

Processing:  69%|██████▊   | 651/947 [13:07<08:01,  1.63s/it]

Saved batch 575 to ../../data/curation_v1/perturbations/cmpds_names/batch_0575.json

Processing:  69%|██████▉   | 652/947 [13:08<07:56,  1.61s/it]

Saved batch 185 to ../../data/curation_v1/perturbations/cmpds_names/batch_0185.json

Processing:  69%|██████▉   | 654/947 [13:09<04:26,  1.10it/s]

Saved batch 419 to ../../data/curation_v1/perturbations/cmpds_names/batch_0419.json
Saved batch 341 to ../../data/curation_v1/perturbations/cmpds_names/batch_0341.json
Saved batch 574 to ../../data/curation_v1/perturbations/cmpds_names/batch_0574.json

Processing:  69%|██████▉   | 656/947 [13:09<02:53,  1.68it/s]

Saved batch 730 to ../../data/curation_v1/perturbations/cmpds_names/batch_0730.json

Processing:  69%|██████▉   | 657/947 [13:14<08:02,  1.66s/it]

Saved batch 576 to ../../data/curation_v1/perturbations/cmpds_names/batch_0576.json

Processing:  69%|██████▉   | 658/947 [13:15<07:22,  1.53s/it]

Saved batch 342 to ../../data/curation_v1/perturbations/cmpds_names/batch_0342.json

Processing:  70%|██████▉   | 659/947 [13:18<08:39,  1.80s/it]

Saved batch 732 to ../../data/curation_v1/perturbations/cmpds_names/batch_0732.json

Processing:  70%|██████▉   | 660/947 [13:19<08:02,  1.68s/it]

Saved batch 731 to ../../data/curation_v1/perturbations/cmpds_names/batch_0731.json

Processing:  70%|██████▉   | 662/947 [13:21<05:44,  1.21s/it]

Saved batch 343 to ../../data/curation_v1/perturbations/cmpds_names/batch_0343.json
Saved batch 187 to ../../data/curation_v1/perturbations/cmpds_names/batch_0187.json

Processing:  70%|███████   | 663/947 [13:25<09:18,  1.97s/it]

Saved batch 186 to ../../data/curation_v1/perturbations/cmpds_names/batch_0186.json

Processing:  70%|███████   | 664/947 [13:27<09:32,  2.02s/it]

Saved batch 420 to ../../data/curation_v1/perturbations/cmpds_names/batch_0420.json

Processing:  70%|███████   | 665/947 [13:27<07:03,  1.50s/it]

Saved batch 577 to ../../data/curation_v1/perturbations/cmpds_names/batch_0577.json

Processing:  70%|███████   | 666/947 [13:28<05:51,  1.25s/it]

Saved batch 733 to ../../data/curation_v1/perturbations/cmpds_names/batch_0733.json

Processing:  70%|███████   | 667/947 [13:28<04:50,  1.04s/it]

Saved batch 344 to ../../data/curation_v1/perturbations/cmpds_names/batch_0344.json

Processing:  71%|███████   | 668/947 [13:33<10:31,  2.26s/it]

Saved batch 421 to ../../data/curation_v1/perturbations/cmpds_names/batch_0421.json

Processing:  71%|███████   | 669/947 [13:35<09:58,  2.15s/it]

Saved batch 734 to ../../data/curation_v1/perturbations/cmpds_names/batch_0734.json

Processing:  71%|███████   | 670/947 [13:36<07:23,  1.60s/it]

Saved batch 188 to ../../data/curation_v1/perturbations/cmpds_names/batch_0188.json

Processing:  71%|███████   | 671/947 [13:36<05:30,  1.20s/it]

Saved batch 578 to ../../data/curation_v1/perturbations/cmpds_names/batch_0578.json

Processing:  71%|███████   | 672/947 [13:40<09:27,  2.06s/it]

Saved batch 345 to ../../data/curation_v1/perturbations/cmpds_names/batch_0345.json

Processing:  71%|███████   | 673/947 [13:43<10:25,  2.28s/it]

Saved batch 579 to ../../data/curation_v1/perturbations/cmpds_names/batch_0579.json

Processing:  71%|███████   | 674/947 [13:44<08:19,  1.83s/it]

Saved batch 423 to ../../data/curation_v1/perturbations/cmpds_names/batch_0423.json

Processing:  71%|███████▏  | 675/947 [13:45<08:24,  1.86s/it]

Saved batch 190 to ../../data/curation_v1/perturbations/cmpds_names/batch_0190.json

Processing:  71%|███████▏  | 676/947 [13:48<09:15,  2.05s/it]

Saved batch 424 to ../../data/curation_v1/perturbations/cmpds_names/batch_0424.json

Processing:  71%|███████▏  | 677/947 [13:51<09:51,  2.19s/it]

Saved batch 422 to ../../data/curation_v1/perturbations/cmpds_names/batch_0422.json

Processing:  72%|███████▏  | 678/947 [13:51<07:40,  1.71s/it]

Saved batch 346 to ../../data/curation_v1/perturbations/cmpds_names/batch_0346.json

Processing:  72%|███████▏  | 679/947 [13:55<11:10,  2.50s/it]

Saved batch 189 to ../../data/curation_v1/perturbations/cmpds_names/batch_0189.json

Processing:  72%|███████▏  | 681/947 [13:58<08:00,  1.81s/it]

Saved batch 347 to ../../data/curation_v1/perturbations/cmpds_names/batch_0347.json
Saved batch 191 to ../../data/curation_v1/perturbations/cmpds_names/batch_0191.json

Processing:  72%|███████▏  | 682/947 [14:00<07:51,  1.78s/it]

Saved batch 736 to ../../data/curation_v1/perturbations/cmpds_names/batch_0736.json

Processing:  72%|███████▏  | 683/947 [14:00<05:52,  1.34s/it]

Saved batch 580 to ../../data/curation_v1/perturbations/cmpds_names/batch_0580.json

Processing:  72%|███████▏  | 685/947 [14:02<04:21,  1.00it/s]

Saved batch 735 to ../../data/curation_v1/perturbations/cmpds_names/batch_0735.json
Saved batch 737 to ../../data/curation_v1/perturbations/cmpds_names/batch_0737.json

Processing:  72%|███████▏  | 686/947 [14:04<05:22,  1.24s/it]

Saved batch 425 to ../../data/curation_v1/perturbations/cmpds_names/batch_0425.json

Processing:  73%|███████▎  | 687/947 [14:06<07:02,  1.62s/it]

Saved batch 348 to ../../data/curation_v1/perturbations/cmpds_names/batch_0348.json

Processing:  73%|███████▎  | 688/947 [14:08<07:09,  1.66s/it]

Saved batch 192 to ../../data/curation_v1/perturbations/cmpds_names/batch_0192.json

Processing:  73%|███████▎  | 689/947 [14:08<05:50,  1.36s/it]

Saved batch 426 to ../../data/curation_v1/perturbations/cmpds_names/batch_0426.json

Processing:  73%|███████▎  | 690/947 [14:10<06:18,  1.47s/it]

Saved batch 3 to ../../data/curation_v1/perturbations/cmpds_names/batch_0003.json

Processing:  73%|███████▎  | 691/947 [14:11<06:02,  1.42s/it]

Saved batch 193 to ../../data/curation_v1/perturbations/cmpds_names/batch_0193.json

Processing:  73%|███████▎  | 692/947 [14:13<06:27,  1.52s/it]

Saved batch 581 to ../../data/curation_v1/perturbations/cmpds_names/batch_0581.json
Saved batch 582 to ../../data/curation_v1/perturbations/cmpds_names/batch_0582.json

Processing:  73%|███████▎  | 694/947 [14:16<05:47,  1.37s/it]

Saved batch 738 to ../../data/curation_v1/perturbations/cmpds_names/batch_0738.json

Processing:  73%|███████▎  | 696/947 [14:19<05:44,  1.37s/it]

Saved batch 8 to ../../data/curation_v1/perturbations/cmpds_names/batch_0008.json
Saved batch 349 to ../../data/curation_v1/perturbations/cmpds_names/batch_0349.json

Processing:  74%|███████▎  | 697/947 [14:22<07:38,  1.83s/it]

Saved batch 350 to ../../data/curation_v1/perturbations/cmpds_names/batch_0350.json

Processing:  74%|███████▎  | 698/947 [14:23<06:08,  1.48s/it]

Saved batch 428 to ../../data/curation_v1/perturbations/cmpds_names/batch_0428.json
Saved batch 427 to ../../data/curation_v1/perturbations/cmpds_names/batch_0427.json

Processing:  74%|███████▍  | 700/947 [14:24<04:46,  1.16s/it]

Saved batch 739 to ../../data/curation_v1/perturbations/cmpds_names/batch_0739.json

Processing:  74%|███████▍  | 701/947 [14:25<04:27,  1.09s/it]

Saved batch 583 to ../../data/curation_v1/perturbations/cmpds_names/batch_0583.json

Processing:  74%|███████▍  | 702/947 [14:28<07:01,  1.72s/it]

Saved batch 194 to ../../data/curation_v1/perturbations/cmpds_names/batch_0194.json

Processing:  74%|███████▍  | 703/947 [14:29<05:32,  1.36s/it]

Saved batch 351 to ../../data/curation_v1/perturbations/cmpds_names/batch_0351.json

Processing:  74%|███████▍  | 704/947 [14:29<04:38,  1.15s/it]

Saved batch 4 to ../../data/curation_v1/perturbations/cmpds_names/batch_0004.json

Processing:  74%|███████▍  | 705/947 [14:30<04:02,  1.00s/it]

Saved batch 9 to ../../data/curation_v1/perturbations/cmpds_names/batch_0009.json

Processing:  75%|███████▍  | 706/947 [14:33<05:40,  1.41s/it]

Saved batch 195 to ../../data/curation_v1/perturbations/cmpds_names/batch_0195.json

Processing:  75%|███████▍  | 708/947 [14:35<04:58,  1.25s/it]

Saved batch 584 to ../../data/curation_v1/perturbations/cmpds_names/batch_0584.json
Saved batch 740 to ../../data/curation_v1/perturbations/cmpds_names/batch_0740.json

Processing:  75%|███████▍  | 709/947 [14:35<03:47,  1.04it/s]

Saved batch 196 to ../../data/curation_v1/perturbations/cmpds_names/batch_0196.json

Processing:  75%|███████▍  | 710/947 [14:36<02:55,  1.35it/s]

Saved batch 741 to ../../data/curation_v1/perturbations/cmpds_names/batch_0741.json

Processing:  75%|███████▌  | 711/947 [14:37<03:13,  1.22it/s]

Saved batch 352 to ../../data/curation_v1/perturbations/cmpds_names/batch_0352.json

Processing:  75%|███████▌  | 712/947 [14:38<04:03,  1.04s/it]

Saved batch 429 to ../../data/curation_v1/perturbations/cmpds_names/batch_0429.json

Processing:  75%|███████▌  | 713/947 [14:39<04:02,  1.04s/it]

Saved batch 430 to ../../data/curation_v1/perturbations/cmpds_names/batch_0430.json

Processing:  75%|███████▌  | 714/947 [14:44<08:18,  2.14s/it]

Saved batch 353 to ../../data/curation_v1/perturbations/cmpds_names/batch_0353.json
Saved batch 742 to ../../data/curation_v1/perturbations/cmpds_names/batch_0742.json

Processing:  76%|███████▌  | 716/947 [14:46<06:44,  1.75s/it]

Saved batch 743 to ../../data/curation_v1/perturbations/cmpds_names/batch_0743.json

Processing:  76%|███████▌  | 717/947 [14:48<06:29,  1.69s/it]

Saved batch 585 to ../../data/curation_v1/perturbations/cmpds_names/batch_0585.json

Processing:  76%|███████▌  | 719/947 [14:49<03:52,  1.02s/it]

Saved batch 197 to ../../data/curation_v1/perturbations/cmpds_names/batch_0197.json
Saved batch 354 to ../../data/curation_v1/perturbations/cmpds_names/batch_0354.json

Processing:  76%|███████▌  | 720/947 [14:49<03:07,  1.21it/s]

Saved batch 587 to ../../data/curation_v1/perturbations/cmpds_names/batch_0587.json

Processing:  76%|███████▌  | 721/947 [14:52<05:11,  1.38s/it]

Saved batch 586 to ../../data/curation_v1/perturbations/cmpds_names/batch_0586.json

Processing:  76%|███████▌  | 722/947 [14:53<04:43,  1.26s/it]

Saved batch 431 to ../../data/curation_v1/perturbations/cmpds_names/batch_0431.json

Processing:  76%|███████▋  | 723/947 [14:54<05:10,  1.39s/it]

Saved batch 432 to ../../data/curation_v1/perturbations/cmpds_names/batch_0432.json

Processing:  76%|███████▋  | 724/947 [14:57<06:58,  1.88s/it]

Saved batch 355 to ../../data/curation_v1/perturbations/cmpds_names/batch_0355.json

Processing:  77%|███████▋  | 725/947 [14:59<06:35,  1.78s/it]

Saved batch 433 to ../../data/curation_v1/perturbations/cmpds_names/batch_0433.json
Saved batch 744 to ../../data/curation_v1/perturbations/cmpds_names/batch_0744.json

Processing:  77%|███████▋  | 727/947 [15:00<04:12,  1.15s/it]

Saved batch 745 to ../../data/curation_v1/perturbations/cmpds_names/batch_0745.json

Processing:  77%|███████▋  | 728/947 [15:00<03:33,  1.03it/s]

Saved batch 589 to ../../data/curation_v1/perturbations/cmpds_names/batch_0589.json

Processing:  77%|███████▋  | 729/947 [15:01<03:29,  1.04it/s]

Saved batch 198 to ../../data/curation_v1/perturbations/cmpds_names/batch_0198.json

Processing:  77%|███████▋  | 730/947 [15:02<03:17,  1.10it/s]

Saved batch 588 to ../../data/curation_v1/perturbations/cmpds_names/batch_0588.json
Saved batch 199 to ../../data/curation_v1/perturbations/cmpds_names/batch_0199.json

Processing:  77%|███████▋  | 732/947 [15:07<05:59,  1.67s/it]

Saved batch 356 to ../../data/curation_v1/perturbations/cmpds_names/batch_0356.json

Processing:  77%|███████▋  | 733/947 [15:07<04:48,  1.35s/it]

Saved batch 0 to ../../data/curation_v1/perturbations/cmpds_names/batch_0000.json

Processing:  78%|███████▊  | 734/947 [15:08<03:46,  1.06s/it]

Saved batch 201 to ../../data/curation_v1/perturbations/cmpds_names/batch_0201.json

Processing:  78%|███████▊  | 735/947 [15:09<04:10,  1.18s/it]

Saved batch 746 to ../../data/curation_v1/perturbations/cmpds_names/batch_0746.json

Processing:  78%|███████▊  | 736/947 [15:12<05:41,  1.62s/it]

Saved batch 200 to ../../data/curation_v1/perturbations/cmpds_names/batch_0200.json

Processing:  78%|███████▊  | 737/947 [15:15<07:34,  2.16s/it]

Saved batch 590 to ../../data/curation_v1/perturbations/cmpds_names/batch_0590.json

Processing:  78%|███████▊  | 739/947 [15:17<04:52,  1.41s/it]

Saved batch 202 to ../../data/curation_v1/perturbations/cmpds_names/batch_0202.json
Saved batch 357 to ../../data/curation_v1/perturbations/cmpds_names/batch_0357.json

Processing:  78%|███████▊  | 740/947 [15:19<05:04,  1.47s/it]

Saved batch 434 to ../../data/curation_v1/perturbations/cmpds_names/batch_0434.json

Processing:  78%|███████▊  | 741/947 [15:19<03:56,  1.15s/it]

Saved batch 747 to ../../data/curation_v1/perturbations/cmpds_names/batch_0747.json

Processing:  78%|███████▊  | 742/947 [15:20<03:45,  1.10s/it]

Saved batch 591 to ../../data/curation_v1/perturbations/cmpds_names/batch_0591.json

Processing:  78%|███████▊  | 743/947 [15:21<03:56,  1.16s/it]

Saved batch 435 to ../../data/curation_v1/perturbations/cmpds_names/batch_0435.json

Processing:  79%|███████▊  | 744/947 [15:22<03:27,  1.02s/it]

Saved batch 358 to ../../data/curation_v1/perturbations/cmpds_names/batch_0358.json

Processing:  79%|███████▊  | 745/947 [15:25<05:57,  1.77s/it]

Saved batch 592 to ../../data/curation_v1/perturbations/cmpds_names/batch_0592.json

Processing:  79%|███████▉  | 746/947 [15:26<04:49,  1.44s/it]

Saved batch 748 to ../../data/curation_v1/perturbations/cmpds_names/batch_0748.json

Processing:  79%|███████▉  | 747/947 [15:27<03:48,  1.14s/it]

Saved batch 203 to ../../data/curation_v1/perturbations/cmpds_names/batch_0203.json

Processing:  79%|███████▉  | 748/947 [15:28<04:00,  1.21s/it]

Saved batch 593 to ../../data/curation_v1/perturbations/cmpds_names/batch_0593.json
Saved batch 204 to ../../data/curation_v1/perturbations/cmpds_names/batch_0204.json

Processing:  79%|███████▉  | 750/947 [15:28<02:27,  1.34it/s]

Saved batch 436 to ../../data/curation_v1/perturbations/cmpds_names/batch_0436.json

Processing:  79%|███████▉  | 751/947 [15:29<02:21,  1.39it/s]

Saved batch 359 to ../../data/curation_v1/perturbations/cmpds_names/batch_0359.json

Processing:  79%|███████▉  | 752/947 [15:32<04:07,  1.27s/it]

Saved batch 749 to ../../data/curation_v1/perturbations/cmpds_names/batch_0749.json

Processing:  80%|███████▉  | 753/947 [15:33<03:51,  1.19s/it]

Saved batch 594 to ../../data/curation_v1/perturbations/cmpds_names/batch_0594.json

Processing:  80%|███████▉  | 755/947 [15:33<02:16,  1.40it/s]

Saved batch 437 to ../../data/curation_v1/perturbations/cmpds_names/batch_0437.json
Saved batch 360 to ../../data/curation_v1/perturbations/cmpds_names/batch_0360.json

Processing:  80%|███████▉  | 756/947 [15:34<02:09,  1.48it/s]

Saved batch 438 to ../../data/curation_v1/perturbations/cmpds_names/batch_0438.json

Processing:  80%|███████▉  | 757/947 [15:35<02:48,  1.12it/s]

Saved batch 750 to ../../data/curation_v1/perturbations/cmpds_names/batch_0750.json

Processing:  80%|████████  | 758/947 [15:38<04:52,  1.55s/it]

Saved batch 751 to ../../data/curation_v1/perturbations/cmpds_names/batch_0751.json

Processing:  80%|████████  | 759/947 [15:39<03:45,  1.20s/it]

Saved batch 205 to ../../data/curation_v1/perturbations/cmpds_names/batch_0205.json

Processing:  80%|████████  | 760/947 [15:40<03:49,  1.23s/it]

Saved batch 595 to ../../data/curation_v1/perturbations/cmpds_names/batch_0595.json

Processing:  80%|████████  | 761/947 [15:41<03:10,  1.02s/it]

Saved batch 361 to ../../data/curation_v1/perturbations/cmpds_names/batch_0361.json

Processing:  80%|████████  | 762/947 [15:41<02:55,  1.06it/s]

Saved batch 439 to ../../data/curation_v1/perturbations/cmpds_names/batch_0439.json

Processing:  81%|████████  | 764/947 [15:43<02:14,  1.37it/s]

Saved batch 206 to ../../data/curation_v1/perturbations/cmpds_names/batch_0206.json
Saved batch 596 to ../../data/curation_v1/perturbations/cmpds_names/batch_0596.json

Processing:  81%|████████  | 765/947 [15:44<02:28,  1.23it/s]

Saved batch 440 to ../../data/curation_v1/perturbations/cmpds_names/batch_0440.json

Processing:  81%|████████  | 766/947 [15:45<03:20,  1.11s/it]

Saved batch 207 to ../../data/curation_v1/perturbations/cmpds_names/batch_0207.json

Processing:  81%|████████  | 767/947 [15:49<06:00,  2.00s/it]

Saved batch 362 to ../../data/curation_v1/perturbations/cmpds_names/batch_0362.json

Processing:  81%|████████  | 768/947 [15:50<04:22,  1.47s/it]

Saved batch 752 to ../../data/curation_v1/perturbations/cmpds_names/batch_0752.json

Processing:  81%|████████  | 769/947 [15:50<03:13,  1.09s/it]

Saved batch 753 to ../../data/curation_v1/perturbations/cmpds_names/batch_0753.json
Saved batch 441 to ../../data/curation_v1/perturbations/cmpds_names/batch_0441.json

Processing:  81%|████████▏ | 771/947 [15:50<02:02,  1.43it/s]

Saved batch 208 to ../../data/curation_v1/perturbations/cmpds_names/batch_0208.json

Processing:  82%|████████▏ | 772/947 [15:51<01:55,  1.51it/s]

Saved batch 597 to ../../data/curation_v1/perturbations/cmpds_names/batch_0597.json

Processing:  82%|████████▏ | 774/947 [15:54<02:33,  1.13it/s]

Saved batch 598 to ../../data/curation_v1/perturbations/cmpds_names/batch_0598.json
Saved batch 442 to ../../data/curation_v1/perturbations/cmpds_names/batch_0442.json

Processing:  82%|████████▏ | 775/947 [15:54<02:22,  1.21it/s]

Saved batch 363 to ../../data/curation_v1/perturbations/cmpds_names/batch_0363.json

Processing:  82%|████████▏ | 776/947 [15:55<02:22,  1.20it/s]

Saved batch 209 to ../../data/curation_v1/perturbations/cmpds_names/batch_0209.json

Processing:  82%|████████▏ | 777/947 [15:56<02:08,  1.33it/s]

Saved batch 364 to ../../data/curation_v1/perturbations/cmpds_names/batch_0364.json

Processing:  82%|████████▏ | 778/947 [15:57<02:22,  1.19it/s]

Saved batch 599 to ../../data/curation_v1/perturbations/cmpds_names/batch_0599.json

Processing:  82%|████████▏ | 779/947 [15:58<02:44,  1.02it/s]

Saved batch 754 to ../../data/curation_v1/perturbations/cmpds_names/batch_0754.json
Saved batch 210 to ../../data/curation_v1/perturbations/cmpds_names/batch_0210.json

Processing:  82%|████████▏ | 781/947 [15:59<02:19,  1.19it/s]

Saved batch 443 to ../../data/curation_v1/perturbations/cmpds_names/batch_0443.json

Processing:  83%|████████▎ | 782/947 [16:01<02:37,  1.05it/s]

Saved batch 756 to ../../data/curation_v1/perturbations/cmpds_names/batch_0756.json

Processing:  83%|████████▎ | 783/947 [16:01<02:15,  1.21it/s]

Saved batch 600 to ../../data/curation_v1/perturbations/cmpds_names/batch_0600.json

Processing:  83%|████████▎ | 784/947 [16:02<02:00,  1.35it/s]

Saved batch 444 to ../../data/curation_v1/perturbations/cmpds_names/batch_0444.json

Processing:  83%|████████▎ | 785/947 [16:02<01:47,  1.51it/s]

Saved batch 755 to ../../data/curation_v1/perturbations/cmpds_names/batch_0755.json

Processing:  83%|████████▎ | 787/947 [16:03<01:23,  1.91it/s]

Saved batch 211 to ../../data/curation_v1/perturbations/cmpds_names/batch_0211.json
Saved batch 365 to ../../data/curation_v1/perturbations/cmpds_names/batch_0365.json

Processing:  83%|████████▎ | 788/947 [16:05<02:17,  1.16it/s]

Saved batch 366 to ../../data/curation_v1/perturbations/cmpds_names/batch_0366.json

Processing:  83%|████████▎ | 789/947 [16:05<01:52,  1.40it/s]

Saved batch 445 to ../../data/curation_v1/perturbations/cmpds_names/batch_0445.json

Processing:  83%|████████▎ | 790/947 [16:09<04:24,  1.69s/it]

Saved batch 757 to ../../data/curation_v1/perturbations/cmpds_names/batch_0757.json

Processing:  84%|████████▎ | 791/947 [16:10<03:36,  1.38s/it]

Saved batch 212 to ../../data/curation_v1/perturbations/cmpds_names/batch_0212.json

Processing:  84%|████████▎ | 792/947 [16:10<02:41,  1.04s/it]

Saved batch 601 to ../../data/curation_v1/perturbations/cmpds_names/batch_0601.json

Processing:  84%|████████▎ | 793/947 [16:12<03:08,  1.22s/it]

Saved batch 2 to ../../data/curation_v1/perturbations/cmpds_names/batch_0002.json

Processing:  84%|████████▍ | 794/947 [16:13<03:15,  1.28s/it]

Saved batch 446 to ../../data/curation_v1/perturbations/cmpds_names/batch_0446.json

Processing:  84%|████████▍ | 795/947 [16:14<02:43,  1.08s/it]

Saved batch 213 to ../../data/curation_v1/perturbations/cmpds_names/batch_0213.json

Processing:  84%|████████▍ | 796/947 [16:15<03:16,  1.30s/it]

Saved batch 758 to ../../data/curation_v1/perturbations/cmpds_names/batch_0758.json

Processing:  84%|████████▍ | 797/947 [16:16<02:37,  1.05s/it]

Saved batch 447 to ../../data/curation_v1/perturbations/cmpds_names/batch_0447.json

Processing:  84%|████████▍ | 798/947 [16:21<05:47,  2.33s/it]

Saved batch 448 to ../../data/curation_v1/perturbations/cmpds_names/batch_0448.json

Processing:  84%|████████▍ | 799/947 [16:22<04:47,  1.94s/it]

Saved batch 759 to ../../data/curation_v1/perturbations/cmpds_names/batch_0759.json

Processing:  84%|████████▍ | 800/947 [16:23<03:44,  1.53s/it]

Saved batch 370 to ../../data/curation_v1/perturbations/cmpds_names/batch_0370.json

Processing:  85%|████████▍ | 801/947 [16:26<04:48,  1.98s/it]

Saved batch 369 to ../../data/curation_v1/perturbations/cmpds_names/batch_0369.json

Processing:  85%|████████▍ | 802/947 [16:27<04:12,  1.74s/it]

Saved batch 214 to ../../data/curation_v1/perturbations/cmpds_names/batch_0214.json

Processing:  85%|████████▍ | 803/947 [16:30<05:12,  2.17s/it]

Saved batch 604 to ../../data/curation_v1/perturbations/cmpds_names/batch_0604.json

Processing:  85%|████████▍ | 804/947 [16:33<05:35,  2.35s/it]

Saved batch 367 to ../../data/curation_v1/perturbations/cmpds_names/batch_0367.json

Processing:  85%|████████▌ | 805/947 [16:35<05:29,  2.32s/it]

Saved batch 449 to ../../data/curation_v1/perturbations/cmpds_names/batch_0449.json

Processing:  85%|████████▌ | 807/947 [16:36<02:56,  1.26s/it]

Saved batch 760 to ../../data/curation_v1/perturbations/cmpds_names/batch_0760.json
Saved batch 605 to ../../data/curation_v1/perturbations/cmpds_names/batch_0605.json

Processing:  85%|████████▌ | 808/947 [16:37<02:47,  1.21s/it]

Saved batch 371 to ../../data/curation_v1/perturbations/cmpds_names/batch_0371.json

Processing:  85%|████████▌ | 809/947 [16:39<03:44,  1.63s/it]

Saved batch 368 to ../../data/curation_v1/perturbations/cmpds_names/batch_0368.json

Processing:  86%|████████▌ | 810/947 [16:40<02:58,  1.30s/it]

Saved batch 215 to ../../data/curation_v1/perturbations/cmpds_names/batch_0215.json

Processing:  86%|████████▌ | 811/947 [16:41<02:33,  1.13s/it]

Saved batch 216 to ../../data/curation_v1/perturbations/cmpds_names/batch_0216.json

Processing:  86%|████████▌ | 812/947 [16:41<02:01,  1.11it/s]

Saved batch 602 to ../../data/curation_v1/perturbations/cmpds_names/batch_0602.json

Processing:  86%|████████▌ | 813/947 [16:42<02:09,  1.03it/s]

Saved batch 603 to ../../data/curation_v1/perturbations/cmpds_names/batch_0603.json

Processing:  86%|████████▌ | 814/947 [16:42<01:38,  1.34it/s]

Saved batch 450 to ../../data/curation_v1/perturbations/cmpds_names/batch_0450.json

Processing:  86%|████████▌ | 815/947 [16:45<02:43,  1.24s/it]

Saved batch 606 to ../../data/curation_v1/perturbations/cmpds_names/batch_0606.json
Saved batch 372 to ../../data/curation_v1/perturbations/cmpds_names/batch_0372.json

Processing:  86%|████████▋ | 817/947 [16:50<03:48,  1.76s/it]

Saved batch 451 to ../../data/curation_v1/perturbations/cmpds_names/batch_0451.json

Processing:  86%|████████▋ | 818/947 [16:51<03:27,  1.61s/it]

Saved batch 607 to ../../data/curation_v1/perturbations/cmpds_names/batch_0607.json

Processing:  86%|████████▋ | 819/947 [16:51<02:57,  1.39s/it]

Saved batch 374 to ../../data/curation_v1/perturbations/cmpds_names/batch_0374.json
Saved batch 217 to ../../data/curation_v1/perturbations/cmpds_names/batch_0217.json

Processing:  87%|████████▋ | 821/947 [16:53<02:16,  1.09s/it]

Saved batch 218 to ../../data/curation_v1/perturbations/cmpds_names/batch_0218.json

Processing:  87%|████████▋ | 822/947 [16:54<02:15,  1.09s/it]

Saved batch 761 to ../../data/curation_v1/perturbations/cmpds_names/batch_0761.json

Processing:  87%|████████▋ | 823/947 [16:56<02:40,  1.29s/it]

Saved batch 373 to ../../data/curation_v1/perturbations/cmpds_names/batch_0373.json

Processing:  87%|████████▋ | 824/947 [16:59<03:27,  1.68s/it]

Saved batch 452 to ../../data/curation_v1/perturbations/cmpds_names/batch_0452.json

Processing:  87%|████████▋ | 825/947 [17:00<03:02,  1.50s/it]

Saved batch 763 to ../../data/curation_v1/perturbations/cmpds_names/batch_0763.json

Processing:  87%|████████▋ | 826/947 [17:02<03:26,  1.71s/it]

Saved batch 219 to ../../data/curation_v1/perturbations/cmpds_names/batch_0219.json

Processing:  87%|████████▋ | 828/947 [17:05<03:11,  1.61s/it]

Saved batch 764 to ../../data/curation_v1/perturbations/cmpds_names/batch_0764.json
Saved batch 453 to ../../data/curation_v1/perturbations/cmpds_names/batch_0453.json

Processing:  88%|████████▊ | 829/947 [17:06<02:26,  1.24s/it]

Saved batch 375 to ../../data/curation_v1/perturbations/cmpds_names/batch_0375.json

Processing:  88%|████████▊ | 830/947 [17:07<02:14,  1.15s/it]

Saved batch 608 to ../../data/curation_v1/perturbations/cmpds_names/batch_0608.json

Processing:  88%|████████▊ | 831/947 [17:12<04:29,  2.32s/it]

Saved batch 220 to ../../data/curation_v1/perturbations/cmpds_names/batch_0220.json

Processing:  88%|████████▊ | 832/947 [17:13<03:29,  1.83s/it]

Saved batch 1 to ../../data/curation_v1/perturbations/cmpds_names/batch_0001.json

Processing:  88%|████████▊ | 833/947 [17:14<03:07,  1.64s/it]

Saved batch 454 to ../../data/curation_v1/perturbations/cmpds_names/batch_0454.json

Processing:  88%|████████▊ | 834/947 [17:17<03:57,  2.10s/it]

Saved batch 609 to ../../data/curation_v1/perturbations/cmpds_names/batch_0609.json

Processing:  88%|████████▊ | 835/947 [17:18<03:08,  1.68s/it]

Saved batch 766 to ../../data/curation_v1/perturbations/cmpds_names/batch_0766.json

Processing:  88%|████████▊ | 836/947 [17:18<02:35,  1.40s/it]

Saved batch 376 to ../../data/curation_v1/perturbations/cmpds_names/batch_0376.json

Processing:  88%|████████▊ | 837/947 [17:19<02:04,  1.13s/it]

Saved batch 765 to ../../data/curation_v1/perturbations/cmpds_names/batch_0765.json

Processing:  88%|████████▊ | 838/947 [17:20<01:55,  1.06s/it]

Saved batch 610 to ../../data/curation_v1/perturbations/cmpds_names/batch_0610.json

Processing:  89%|████████▊ | 839/947 [17:22<02:19,  1.29s/it]

Saved batch 221 to ../../data/curation_v1/perturbations/cmpds_names/batch_0221.json

Processing:  89%|████████▊ | 840/947 [17:25<03:21,  1.89s/it]

Saved batch 377 to ../../data/curation_v1/perturbations/cmpds_names/batch_0377.json

Processing:  89%|████████▉ | 841/947 [17:26<03:02,  1.72s/it]

Saved batch 762 to ../../data/curation_v1/perturbations/cmpds_names/batch_0762.json

Processing:  89%|████████▉ | 842/947 [17:29<03:22,  1.92s/it]

Saved batch 611 to ../../data/curation_v1/perturbations/cmpds_names/batch_0611.json

Processing:  89%|████████▉ | 843/947 [17:30<02:50,  1.64s/it]

Saved batch 455 to ../../data/curation_v1/perturbations/cmpds_names/batch_0455.json

Processing:  89%|████████▉ | 844/947 [17:32<03:01,  1.76s/it]

Saved batch 768 to ../../data/curation_v1/perturbations/cmpds_names/batch_0768.json

Processing:  89%|████████▉ | 845/947 [17:32<02:32,  1.49s/it]

Saved batch 222 to ../../data/curation_v1/perturbations/cmpds_names/batch_0222.json

Processing:  89%|████████▉ | 846/947 [17:33<01:58,  1.18s/it]

Saved batch 378 to ../../data/curation_v1/perturbations/cmpds_names/batch_0378.json

Processing:  89%|████████▉ | 847/947 [17:35<02:21,  1.41s/it]

Saved batch 612 to ../../data/curation_v1/perturbations/cmpds_names/batch_0612.json

Processing:  90%|████████▉ | 848/947 [17:36<02:17,  1.38s/it]

Saved batch 767 to ../../data/curation_v1/perturbations/cmpds_names/batch_0767.json

Processing:  90%|████████▉ | 849/947 [17:38<02:35,  1.59s/it]

Saved batch 456 to ../../data/curation_v1/perturbations/cmpds_names/batch_0456.json

Processing:  90%|████████▉ | 850/947 [17:39<02:11,  1.35s/it]

Saved batch 457 to ../../data/curation_v1/perturbations/cmpds_names/batch_0457.json

Processing:  90%|████████▉ | 851/947 [17:39<01:38,  1.03s/it]

Saved batch 613 to ../../data/curation_v1/perturbations/cmpds_names/batch_0613.json

Processing:  90%|████████▉ | 852/947 [17:41<02:04,  1.31s/it]

Saved batch 769 to ../../data/curation_v1/perturbations/cmpds_names/batch_0769.json

Processing:  90%|█████████ | 853/947 [17:44<02:41,  1.72s/it]

Saved batch 380 to ../../data/curation_v1/perturbations/cmpds_names/batch_0380.json

Processing:  90%|█████████ | 854/947 [17:45<02:26,  1.58s/it]

Saved batch 379 to ../../data/curation_v1/perturbations/cmpds_names/batch_0379.json

Processing:  90%|█████████ | 855/947 [17:49<03:24,  2.22s/it]

Saved batch 614 to ../../data/curation_v1/perturbations/cmpds_names/batch_0614.json

Processing:  90%|█████████ | 856/947 [17:50<02:38,  1.74s/it]

Saved batch 223 to ../../data/curation_v1/perturbations/cmpds_names/batch_0223.json

Processing:  90%|█████████ | 857/947 [17:51<02:32,  1.69s/it]

Saved batch 381 to ../../data/curation_v1/perturbations/cmpds_names/batch_0381.json

Processing:  91%|█████████ | 858/947 [17:52<02:08,  1.44s/it]

Saved batch 615 to ../../data/curation_v1/perturbations/cmpds_names/batch_0615.json

Processing:  91%|█████████ | 859/947 [17:53<01:59,  1.36s/it]

Saved batch 458 to ../../data/curation_v1/perturbations/cmpds_names/batch_0458.json

Processing:  91%|█████████ | 860/947 [17:55<02:10,  1.50s/it]

Saved batch 224 to ../../data/curation_v1/perturbations/cmpds_names/batch_0224.json

Processing:  91%|█████████ | 862/947 [17:58<01:51,  1.31s/it]

Saved batch 771 to ../../data/curation_v1/perturbations/cmpds_names/batch_0771.json
Saved batch 770 to ../../data/curation_v1/perturbations/cmpds_names/batch_0770.json
Saved batch 225 to ../../data/curation_v1/perturbations/cmpds_names/batch_0225.json

Processing:  91%|█████████ | 864/947 [17:58<01:05,  1.26it/s]

Saved batch 459 to ../../data/curation_v1/perturbations/cmpds_names/batch_0459.json

Processing:  91%|█████████▏| 865/947 [18:02<02:08,  1.57s/it]

Saved batch 772 to ../../data/curation_v1/perturbations/cmpds_names/batch_0772.json

Processing:  91%|█████████▏| 866/947 [18:03<01:52,  1.38s/it]

Saved batch 227 to ../../data/curation_v1/perturbations/cmpds_names/batch_0227.json

Processing:  92%|█████████▏| 867/947 [18:03<01:25,  1.07s/it]

Saved batch 226 to ../../data/curation_v1/perturbations/cmpds_names/batch_0226.json

Processing:  92%|█████████▏| 868/947 [18:04<01:26,  1.09s/it]

Saved batch 616 to ../../data/curation_v1/perturbations/cmpds_names/batch_0616.json

Processing:  92%|█████████▏| 869/947 [18:06<01:44,  1.33s/it]

Saved batch 461 to ../../data/curation_v1/perturbations/cmpds_names/batch_0461.json

Processing:  92%|█████████▏| 870/947 [18:08<01:49,  1.42s/it]

Saved batch 460 to ../../data/curation_v1/perturbations/cmpds_names/batch_0460.json

Processing:  92%|█████████▏| 871/947 [18:09<01:48,  1.43s/it]

Saved batch 382 to ../../data/curation_v1/perturbations/cmpds_names/batch_0382.json

Processing:  92%|█████████▏| 872/947 [18:16<03:52,  3.09s/it]

Saved batch 228 to ../../data/curation_v1/perturbations/cmpds_names/batch_0228.json

Processing:  92%|█████████▏| 873/947 [18:17<03:06,  2.53s/it]

Saved batch 462 to ../../data/curation_v1/perturbations/cmpds_names/batch_0462.json

Processing:  92%|█████████▏| 874/947 [18:21<03:24,  2.80s/it]

Saved batch 383 to ../../data/curation_v1/perturbations/cmpds_names/batch_0383.json

Processing:  92%|█████████▏| 875/947 [18:21<02:27,  2.05s/it]

Saved batch 229 to ../../data/curation_v1/perturbations/cmpds_names/batch_0229.json

Processing:  93%|█████████▎| 876/947 [18:22<02:07,  1.79s/it]

Saved batch 773 to ../../data/curation_v1/perturbations/cmpds_names/batch_0773.json

Processing:  93%|█████████▎| 877/947 [18:24<01:59,  1.71s/it]

Saved batch 617 to ../../data/curation_v1/perturbations/cmpds_names/batch_0617.json

Processing:  93%|█████████▎| 878/947 [18:24<01:29,  1.29s/it]

Saved batch 618 to ../../data/curation_v1/perturbations/cmpds_names/batch_0618.json

Processing:  93%|█████████▎| 879/947 [18:26<01:37,  1.43s/it]

Saved batch 774 to ../../data/curation_v1/perturbations/cmpds_names/batch_0774.json

Processing:  93%|█████████▎| 880/947 [18:26<01:12,  1.07s/it]

Saved batch 385 to ../../data/curation_v1/perturbations/cmpds_names/batch_0385.json

Processing:  93%|█████████▎| 881/947 [18:31<02:20,  2.12s/it]

Saved batch 775 to ../../data/curation_v1/perturbations/cmpds_names/batch_0775.json

Processing:  93%|█████████▎| 882/947 [18:33<02:12,  2.04s/it]

Saved batch 463 to ../../data/curation_v1/perturbations/cmpds_names/batch_0463.json
Saved batch 230 to ../../data/curation_v1/perturbations/cmpds_names/batch_0230.json

Processing:  93%|█████████▎| 884/947 [18:34<01:31,  1.45s/it]

Saved batch 386 to ../../data/curation_v1/perturbations/cmpds_names/batch_0386.json

Processing:  93%|█████████▎| 885/947 [18:35<01:23,  1.35s/it]

Saved batch 619 to ../../data/curation_v1/perturbations/cmpds_names/batch_0619.json

Processing:  94%|█████████▎| 886/947 [18:42<02:44,  2.70s/it]

Saved batch 776 to ../../data/curation_v1/perturbations/cmpds_names/batch_0776.json

Processing:  94%|█████████▎| 887/947 [18:42<02:07,  2.12s/it]

Saved batch 853 to ../../data/curation_v1/perturbations/cmpds_names/batch_0853.json

Processing:  94%|█████████▍| 888/947 [18:43<01:46,  1.81s/it]

Saved batch 231 to ../../data/curation_v1/perturbations/cmpds_names/batch_0231.json

Processing:  94%|█████████▍| 889/947 [18:44<01:31,  1.57s/it]

Saved batch 464 to ../../data/curation_v1/perturbations/cmpds_names/batch_0464.json

Processing:  94%|█████████▍| 890/947 [18:45<01:20,  1.41s/it]

Saved batch 620 to ../../data/curation_v1/perturbations/cmpds_names/batch_0620.json

Processing:  94%|█████████▍| 891/947 [18:47<01:21,  1.45s/it]

Saved batch 384 to ../../data/curation_v1/perturbations/cmpds_names/batch_0384.json

Processing:  94%|█████████▍| 892/947 [18:49<01:24,  1.53s/it]

Saved batch 777 to ../../data/curation_v1/perturbations/cmpds_names/batch_0777.json

Processing:  94%|█████████▍| 893/947 [18:49<01:12,  1.34s/it]

Saved batch 465 to ../../data/curation_v1/perturbations/cmpds_names/batch_0465.json

Processing:  94%|█████████▍| 894/947 [18:50<00:54,  1.03s/it]

Saved batch 232 to ../../data/curation_v1/perturbations/cmpds_names/batch_0232.json

Processing:  95%|█████████▍| 895/947 [18:53<01:29,  1.71s/it]

Saved batch 621 to ../../data/curation_v1/perturbations/cmpds_names/batch_0621.json

Processing:  95%|█████████▍| 896/947 [18:58<02:13,  2.63s/it]

Saved batch 388 to ../../data/curation_v1/perturbations/cmpds_names/batch_0388.json

Processing:  95%|█████████▍| 897/947 [18:59<01:55,  2.32s/it]

Saved batch 466 to ../../data/curation_v1/perturbations/cmpds_names/batch_0466.json

Processing:  95%|█████████▍| 899/947 [19:00<01:01,  1.28s/it]

Saved batch 467 to ../../data/curation_v1/perturbations/cmpds_names/batch_0467.json
Saved batch 387 to ../../data/curation_v1/perturbations/cmpds_names/batch_0387.json

Processing:  95%|█████████▌| 900/947 [19:02<01:06,  1.42s/it]

Saved batch 389 to ../../data/curation_v1/perturbations/cmpds_names/batch_0389.json

Processing:  95%|█████████▌| 901/947 [19:04<01:09,  1.51s/it]

Saved batch 778 to ../../data/curation_v1/perturbations/cmpds_names/batch_0778.json

Processing:  95%|█████████▌| 902/947 [19:04<00:58,  1.30s/it]

Saved batch 622 to ../../data/curation_v1/perturbations/cmpds_names/batch_0622.json

Processing:  95%|█████████▌| 903/947 [19:08<01:24,  1.92s/it]

Saved batch 468 to ../../data/curation_v1/perturbations/cmpds_names/batch_0468.json

Processing:  95%|█████████▌| 904/947 [19:09<01:08,  1.60s/it]

Saved batch 623 to ../../data/curation_v1/perturbations/cmpds_names/batch_0623.json

Processing:  96%|█████████▌| 905/947 [19:10<01:08,  1.62s/it]

Saved batch 234 to ../../data/curation_v1/perturbations/cmpds_names/batch_0234.json

Processing:  96%|█████████▌| 906/947 [19:11<00:51,  1.26s/it]

Saved batch 233 to ../../data/curation_v1/perturbations/cmpds_names/batch_0233.json

Processing:  96%|█████████▌| 907/947 [19:14<01:09,  1.74s/it]

Saved batch 235 to ../../data/curation_v1/perturbations/cmpds_names/batch_0235.json

Processing:  96%|█████████▌| 908/947 [19:14<00:51,  1.33s/it]

Saved batch 469 to ../../data/curation_v1/perturbations/cmpds_names/batch_0469.json

Processing:  96%|█████████▌| 909/947 [19:14<00:40,  1.06s/it]

Saved batch 390 to ../../data/curation_v1/perturbations/cmpds_names/batch_0390.json

Processing:  96%|█████████▌| 910/947 [19:15<00:37,  1.01s/it]

Saved batch 391 to ../../data/curation_v1/perturbations/cmpds_names/batch_0391.json

Processing:  96%|█████████▌| 911/947 [19:18<00:54,  1.51s/it]

Saved batch 624 to ../../data/curation_v1/perturbations/cmpds_names/batch_0624.json

Processing:  96%|█████████▋| 912/947 [19:19<00:43,  1.24s/it]

Saved batch 779 to ../../data/curation_v1/perturbations/cmpds_names/batch_0779.json

Processing:  96%|█████████▋| 913/947 [19:24<01:21,  2.39s/it]

Saved batch 470 to ../../data/curation_v1/perturbations/cmpds_names/batch_0470.json

Processing:  97%|█████████▋| 914/947 [19:25<01:06,  2.02s/it]

Saved batch 236 to ../../data/curation_v1/perturbations/cmpds_names/batch_0236.json

Processing:  97%|█████████▋| 915/947 [19:26<00:58,  1.83s/it]

Saved batch 392 to ../../data/curation_v1/perturbations/cmpds_names/batch_0392.json

Processing:  97%|█████████▋| 916/947 [19:29<01:04,  2.08s/it]

Saved batch 780 to ../../data/curation_v1/perturbations/cmpds_names/batch_0780.json
Saved batch 393 to ../../data/curation_v1/perturbations/cmpds_names/batch_0393.json

Processing:  97%|█████████▋| 918/947 [19:34<01:08,  2.36s/it]

Saved batch 237 to ../../data/curation_v1/perturbations/cmpds_names/batch_0237.json

Processing:  97%|█████████▋| 919/947 [19:35<00:57,  2.06s/it]

Saved batch 471 to ../../data/curation_v1/perturbations/cmpds_names/batch_0471.json

Processing:  97%|█████████▋| 920/947 [19:38<00:56,  2.11s/it]

Saved batch 238 to ../../data/curation_v1/perturbations/cmpds_names/batch_0238.json

Processing:  97%|█████████▋| 921/947 [19:42<01:07,  2.61s/it]

Saved batch 394 to ../../data/curation_v1/perturbations/cmpds_names/batch_0394.json

Processing:  97%|█████████▋| 922/947 [19:43<00:57,  2.32s/it]

Saved batch 783 to ../../data/curation_v1/perturbations/cmpds_names/batch_0783.json

Processing:  97%|█████████▋| 923/947 [19:44<00:45,  1.90s/it]

Saved batch 781 to ../../data/curation_v1/perturbations/cmpds_names/batch_0781.json

Processing:  98%|█████████▊| 924/947 [19:48<01:00,  2.64s/it]

Saved batch 472 to ../../data/curation_v1/perturbations/cmpds_names/batch_0472.json

Processing:  98%|█████████▊| 925/947 [19:50<00:49,  2.23s/it]

Saved batch 473 to ../../data/curation_v1/perturbations/cmpds_names/batch_0473.json

Processing:  98%|█████████▊| 926/947 [19:54<00:57,  2.76s/it]

Saved batch 239 to ../../data/curation_v1/perturbations/cmpds_names/batch_0239.json

Processing:  98%|█████████▊| 927/947 [19:54<00:40,  2.04s/it]

Saved batch 628 to ../../data/curation_v1/perturbations/cmpds_names/batch_0628.json

Processing:  98%|█████████▊| 928/947 [19:56<00:37,  1.96s/it]

Saved batch 784 to ../../data/curation_v1/perturbations/cmpds_names/batch_0784.json

Processing:  98%|█████████▊| 929/947 [19:56<00:27,  1.50s/it]

Saved batch 395 to ../../data/curation_v1/perturbations/cmpds_names/batch_0395.json

Processing:  98%|█████████▊| 930/947 [19:59<00:32,  1.90s/it]

Saved batch 629 to ../../data/curation_v1/perturbations/cmpds_names/batch_0629.json

Processing:  98%|█████████▊| 931/947 [20:03<00:41,  2.57s/it]

Saved batch 396 to ../../data/curation_v1/perturbations/cmpds_names/batch_0396.json

Processing:  98%|█████████▊| 932/947 [20:04<00:29,  1.96s/it]

Saved batch 785 to ../../data/curation_v1/perturbations/cmpds_names/batch_0785.json

Processing:  99%|█████████▊| 933/947 [20:05<00:24,  1.74s/it]

Saved batch 474 to ../../data/curation_v1/perturbations/cmpds_names/batch_0474.json

Processing:  99%|█████████▊| 934/947 [20:07<00:23,  1.81s/it]

Saved batch 625 to ../../data/curation_v1/perturbations/cmpds_names/batch_0625.json

Processing:  99%|█████████▊| 935/947 [20:08<00:19,  1.61s/it]

Saved batch 782 to ../../data/curation_v1/perturbations/cmpds_names/batch_0782.json

Processing:  99%|█████████▉| 936/947 [20:10<00:17,  1.59s/it]

Saved batch 7 to ../../data/curation_v1/perturbations/cmpds_names/batch_0007.json

Processing:  99%|█████████▉| 937/947 [20:10<00:13,  1.37s/it]

Saved batch 630 to ../../data/curation_v1/perturbations/cmpds_names/batch_0630.json

Processing:  99%|█████████▉| 938/947 [20:14<00:17,  1.89s/it]

Saved batch 786 to ../../data/curation_v1/perturbations/cmpds_names/batch_0786.json

Processing:  99%|█████████▉| 940/947 [20:14<00:07,  1.03s/it]

Saved batch 475 to ../../data/curation_v1/perturbations/cmpds_names/batch_0475.json
Saved batch 397 to ../../data/curation_v1/perturbations/cmpds_names/batch_0397.json

Processing:  99%|█████████▉| 941/947 [20:14<00:04,  1.23it/s]

Saved batch 626 to ../../data/curation_v1/perturbations/cmpds_names/batch_0626.json
Saved batch 6 to ../../data/curation_v1/perturbations/cmpds_names/batch_0006.json

Processing: 100%|█████████▉| 943/947 [20:15<00:02,  1.45it/s]

Saved batch 627 to ../../data/curation_v1/perturbations/cmpds_names/batch_0627.json

Processing: 100%|█████████▉| 944/947 [20:16<00:01,  1.66it/s]

Saved batch 240 to ../../data/curation_v1/perturbations/cmpds_names/batch_0240.json

Processing: 100%|█████████▉| 945/947 [20:19<00:02,  1.22s/it]

Saved batch 241 to ../../data/curation_v1/perturbations/cmpds_names/batch_0241.json

Processing: 100%|█████████▉| 946/947 [20:19<00:01,  1.04s/it]

Saved batch 631 to ../../data/curation_v1/perturbations/cmpds_names/batch_0631.json

Processing: 100%|██████████| 947/947 [20:25<00:00,  1.29s/it]

Saved batch 787 to ../../data/curation_v1/perturbations/cmpds_names/batch_0787.json
Processed 947 new batches
Total results: 9452 molecules
Consolidated results saved to: ../../data/curation_v1/perturbations/cmpds_names/all_results.json

In [14]:
# Optional: Save results to file
output_path = "/Users/emmanuel.noutahi/Code/hooke-explain/data/curation_v1/perturbations/molecules_top_names_sample.tsv"
final_df.to_csv(output_path, index=False)

In [15]:
aboutamol = pd.read_parquet("../../data/curation_v1/perturbations/aboutamol.parquet")

In [23]:
from rdkit.Chem import AllChem


def to_inchi_key(smiles):
    try:
        return AllChem.MolToInchiKey(AllChem.MolFromSmiles(smiles))
    except Exception:
        return None


final_df["inchi_key"] = final_df["smiles"].apply(to_inchi_key)

[14:43:03] SMILES Parse Error: unclosed ring for input: 'CC1=NC2=C(N1)C(=O)N1CCOC(C1)C(O)=O'
[14:43:03] Explicit valence for atom # 6 C, 5, is greater than permitted
[14:43:03] SMILES Parse Error: extra close parentheses while parsing: COC1=CC(CNC(=O)NC2=CC=C(Cl)C=C2)N2CCCC2)=CC=C1
[14:43:03] SMILES Parse Error: check for mistakes around position 40:
[14:43:03] CC=C(Cl)C=C2)N2CCCC2)=CC=C1
[14:43:03] ~~~~~~~~~~~~~~~~~~~~^
[14:43:03] SMILES Parse Error: Failed parsing SMILES 'COC1=CC(CNC(=O)NC2=CC=C(Cl)C=C2)N2CCCC2)=CC=C1' for input: 'COC1=CC(CNC(=O)NC2=CC=C(Cl)C=C2)N2CCCC2)=CC=C1'
[14:43:03] SMILES Parse Error: unclosed ring for input: 'COC1=CC=C(N2C(SCCCN3C(=O)C4=CC=CC5=C4C=CC=C5)NN=C2C2=CC=NC=C2)C=C1'
[14:43:04] SMILES Parse Error: extra open parentheses while parsing: [H][C@@]12CCCN1C(=O)[C@H](C(C)C)NC(=O)[C@@H](NC(=O)C1=CC=C(C)C3=C1N=C1C(=C(C)C(=O)C(N)=C1C(=O)N[C@H]1[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C(=O)[C@]4([H])CCCN4C(=O)[C@H](C(C)C)NC1=O)[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C2=O
[14:43:04] SMILES Parse Error: check for mistakes around position 45:
[14:43:04] ](C(C)C)NC(=O)[C@@H](NC(=O)C1=CC=C(C)C3=C
[14:43:04] ~~~~~~~~~~~~~~~~~~~~^
[14:43:04] SMILES Parse Error: Failed parsing SMILES '[H][C@@]12CCCN1C(=O)[C@H](C(C)C)NC(=O)[C@@H](NC(=O)C1=CC=C(C)C3=C1N=C1C(=C(C)C(=O)C(N)=C1C(=O)N[C@H]1[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C(=O)[C@]4([H])CCCN4C(=O)[C@H](C(C)C)NC1=O)[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C2=O' for input: '[H][C@@]12CCCN1C(=O)[C@H](C(C)C)NC(=O)[C@@H](NC(=O)C1=CC=C(C)C3=C1N=C1C(=C(C)C(=O)C(N)=C1C(=O)N[C@H]1[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C(=O)[C@]4([H])CCCN4C(=O)[C@H](C(C)C)NC1=O)[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C2=O'

In [25]:
grouped_df["inchi_key"] = grouped_df["smiles"].apply(to_inchi_key)

In [57]:
final_df_picked = final_df[(final_df.smiles.isin(grouped_df.smiles)) & (~final_df.duplicated(subset="smiles"))]
final_df_picked.to_csv(output_path, index=False)

In [73]:
tmp_grouped_df = grouped_df[~grouped_df.smiles.isin(final_df_picked.smiles)]
tmp_results_df = await process_with_checkpoint(
    client,
    tmp_grouped_df,
    batch_size=5,
    max_batches=None,  # Set to None for full dataset
    max_concurrent=5,
    checkpoint_dir="../../data/curation_v1/perturbations/cmpds_names_v2/",
)
final_df_recomputed = create_final_dataframe(tmp_results_df)

Found 39 existing results from 8 batch files
Processing 1 new batches (4 molecules)
Processing batches (each batch saved immediately)...

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

Processing: 100%|██████████| 1/1 [00:07<00:00,  7.26s/it]

Saved batch 8 to ../../data/curation_v1/perturbations/cmpds_names_v2/batch_0008.json
Processed 1 new batches
Total results: 43 molecules
Consolidated results saved to: ../../data/curation_v1/perturbations/cmpds_names_v2/all_results.json

In [80]:
tmp = final_df_recomputed.copy()


def recheck_smiles(row):
    # this is to fix wrong prompt design -_-
    if row.smiles in grouped_df.smiles:
        return row.smiles  # nothing to do, LLM did not hallunicate output
    # find the most likely smiles in groupe_df
    top_names = (row.top_name_1, row.top_name_2, row.top_name_3)
    if top_names == (None, None, None):
        return None
    # Find the row in grouped_df whose synonym_list has the most overlap with top_names
    overlap_counts = grouped_df["synonym_list"].apply(lambda syn: len([x for x in top_names if x in syn]))
    max_count = overlap_counts.max()
    if max_count > 0 and (overlap_counts == max_count).sum() == 1:
        best_idx = overlap_counts.idxmax()
        return grouped_df.loc[best_idx, "smiles"]
    else:
        print(f"No unique match found for {row.smiles}")
    return None


tmp["smiles"] = tmp.apply(recheck_smiles, axis=1)

No unique match found for [H][C@@]12CCCN1C(=O)[C@H](C(C)C)NC(=O)[C@@H](NC(=O)C1=CC=C(C)C3=C1N=C1C(=C(C)C(=O)C(N)=C1C(=O)N[C@H]1[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C(=O)[C@]4([H])CCCN4C(=O)[C@H](C(C)C)NC1=O)[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C2=O
No unique match found for [H][C@@]12CCCN1C(=O)[C@H](C(C)C)NC(=O)[C@@H](NC(=O)C1=CC=C(C)C3=C1N=C1C(=C(C)C(=O)C(N)=C1C(=O)N[C@H]1[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C(=O)[C@]4([H])CCCN4C(=O)[C@H](C(C)C)NC1=O)O3)[C@@H](C)OC(=O)[C@H](C(C)C)N(C)C(=O)CN(C)C2=O

In [83]:
tmp = tmp.dropna(subset="smiles")
final_df_picked = pd.concat([final_df_picked, tmp])

In [88]:
final_df_picked[final_df.duplicated("smiles")]

/var/folders/rl/wwcfdj4x0pg293bfqszl970r0000gq/T/ipykernel_23298/104208150.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  final_df_picked[final_df.duplicated("smiles")]

Empty DataFrame
Columns: [smiles, top_name_1, top_name_2, top_name_3, reason_1, reason_2, reason_3, inchi_key]
Index: []

In [91]:
final_df_picked = grouped_df.merge(final_df_picked.drop(columns="inchi_key"), on="smiles", how="left")

In [92]:
final_df_picked.to_parquet(
    "/Users/emmanuel.noutahi/Code/hooke-explain/data/curation_v1/perturbations/molecules_selected.parquet"
)

In [126]:
filtered_aboutamol = aboutamol[aboutamol.inchi_key.isin(grouped_df.inchi_key) & (aboutamol.less_than_10um is True)]
filtered_aboutamol.to_parquet(
    "/Users/emmanuel.noutahi/Code/hooke-explain/data/curation_v1/perturbations/potentially_active.parquet"
)

In [ ]:
from collections import defaultdict

import numpy as np
import pandas as pd

# Potency direction sets
LOWER_IS_BETTER = {"IC50", "EC50", "Ki", "Kd"}
HIGHER_IS_BETTER = {"pIC50", "pEC50", "pKi", "pKd"}


def _ascending_for_mt(mt: str) -> bool:
    """True if lower values mean more potent."""
    return str(mt) in LOWER_IS_BETTER


def _targets_list(t):
    if pd.isna(t) or t is None:
        return []
    return [x.strip() for x in str(t).replace("|", ";").split(";") if x.strip()]


def _rank_score_row(mt, vmin, vmax):
    """Higher score = more potent (for sorting descending)."""
    if _ascending_for_mt(mt):
        return -float(vmin)  # lower is better
    return float(vmax)  # higher is better for pX


def _diverse_round_robin(ordered_df, target_col="mce_target", k=10):
    """Round-robin selection to ensure target diversity."""
    buckets = defaultdict(list)
    for i, t in enumerate(ordered_df[target_col].tolist()):
        toks = _targets_list(t)
        buckets[toks[0] if toks else "__unknown__"].append(i)
    picks, keys = [], list(buckets.keys())
    while len(picks) < min(k, len(ordered_df)):
        advanced = False
        for bk in keys:
            if buckets[bk]:
                picks.append(buckets[bk].pop(0))
                advanced = True
                if len(picks) >= k:
                    break
        if not advanced:
            break
    if len(picks) < min(k, len(ordered_df)):
        for i in range(len(ordered_df)):
            if i not in picks:
                picks.append(i)
            if len(picks) >= k:
                break
    return ordered_df.iloc[picks].reset_index(drop=True)


def _pick_top_with_priority(groups_df: pd.DataFrame, k: int = 10) -> pd.DataFrame:
    """Priority: human+gene > human(no gene) > other species; then diverse & potent."""
    if groups_df.empty:
        return groups_df

    def _order(df):
        return df.sort_values("rank_score", ascending=False, kind="mergesort").reset_index(drop=True)

    b1 = groups_df[
        (groups_df["bioref_organism"] == "Homo sapiens")
        & groups_df["bioref_gene_name"].notna()
        & (groups_df["bioref_gene_name"] != "")
    ]
    b2 = groups_df[
        (groups_df["bioref_organism"] == "Homo sapiens")
        & ~((groups_df["bioref_gene_name"].notna()) & (groups_df["bioref_gene_name"] != ""))
    ]
    b3 = groups_df[groups_df["bioref_organism"] != "Homo sapiens"]

    out, remain = [], k
    for bucket in (_order(b1), _order(b2), _order(b3)):
        if remain <= 0 or bucket.empty:
            continue
        part = _diverse_round_robin(bucket, k=remain)
        out.append(part)
        remain -= len(part)

    return pd.concat(out, ignore_index=True) if out else groups_df.iloc[0:0]


def _collect_sources(df_sub: pd.DataFrame, mt: str):
    """
    Keep only `source` and `publication_doi`, at most 5 entries.
    Selection based on top potency (lowest for IC50/etc., highest for pIC50/etc.).
    """
    cols = ["bioref_source_name", "bioref_article_doi", "bioref_std_measurement_value"]
    have = [c for c in cols if c in df_sub.columns]
    if not have:
        return []

    asc = _ascending_for_mt(mt)
    df_sorted = df_sub.sort_values("bioref_std_measurement_value", ascending=asc, na_position="last")

    seen, out = set(), []
    for _, r in df_sorted.iterrows():
        item = {
            "source": r.get("bioref_source_name"),
            "publication_doi": r.get("bioref_article_doi"),
        }
        key = (item["source"], item["publication_doi"])
        if key not in seen:
            seen.add(key)
            out.append(item)
        if len(out) >= 5:
            break
    return out


def build_pertubation_bioactivities(row):
    """Return compact JSON with aggregated bioactivities and top sources."""
    # ---- synonyms ----
    syns = [row.get("top_name_1"), row.get("top_name_2"), row.get("top_name_3")]
    syns = [s for s in syns if pd.notna(s)]
    extra = row.get("synonym_list", []) or []
    if isinstance(extra, list | tuple) and len(extra) > 0:
        k = min(2, len(extra))
        syns.extend(np.random.choice(extra, size=k, replace=False).tolist())
    synonym_names = sorted(set(syns))

    # ---- fetch activities ----
    tmp_act = filtered_aboutamol[filtered_aboutamol["inchi_key"] == row["inchi_key"]].copy()

    # drop unused
    tmp_act = tmp_act.drop(
        columns=[
            c
            for c in [
                "bioref_original_measurement_value",
                "general_kce",
                "less_than_10um",
                "mce_vendor_id",
                "bioref_original_measurement_unit",
            ]
            if c in tmp_act.columns
        ],
        errors="ignore",
    )

    # ensure required cols
    for c in [
        "mce_target",
        "bioref_gene_name",
        "bioref_organism",
        "bioref_measurement_type",
        "bioref_std_measurement_value",
        "bioref_std_measurement_unit",
        "bioref_source_name",
        "bioref_article_doi",
    ]:
        if c not in tmp_act.columns:
            tmp_act[c] = pd.NA

    # numeric std only
    tmp_act["bioref_std_measurement_value"] = pd.to_numeric(tmp_act["bioref_std_measurement_value"], errors="coerce")
    tmp_act = tmp_act.dropna(subset=["bioref_std_measurement_value"]).copy()
    if tmp_act.empty:
        return json.dumps(
            {
                "synonym_names": synonym_names,
                "smiles": row["smiles"],
                "inchi_key": row["inchi_key"],
                "bioactivities": {"info": {}, "aggregates": []},
            },
            separators=(",", ":"),
        )

    # ---- hoist mce_* info ----
    info = {}
    for f in [
        "mce_product_name",
        "mce_clinical_phase",
        "mce_research_area",
        "mce_pathway",
        "mce_biological_activity",
        "mce_target",
    ]:
        if f in tmp_act.columns:
            vals = [v for v in tmp_act[f].dropna().unique().tolist() if v not in (None, "", "null")]
            if len(vals) == 1:
                info[f] = vals[0]
            elif len(vals) > 1:
                info[f] = " | ".join(sorted(map(str, vals)))

    # ---- aggregate by (target, org, type, unit, gene) ----
    gb = tmp_act.groupby(
        ["mce_target", "bioref_organism", "bioref_measurement_type", "bioref_std_measurement_unit", "bioref_gene_name"],
        dropna=False,
        as_index=False,
    ).agg(
        count=("bioref_std_measurement_value", "size"),
        min=("bioref_std_measurement_value", "min"),
        median=("bioref_std_measurement_value", "median"),
        max=("bioref_std_measurement_value", "max"),
    )

    gb["rank_score"] = [
        _rank_score_row(mt if pd.notna(mt) else "IC50", vmin, vmax)
        for mt, vmin, vmax in zip(gb["bioref_measurement_type"], gb["min"], gb["max"], strict=False)
    ]

    gb_sel = _pick_top_with_priority(gb)

    # ---- build aggregates ----
    aggregates = []
    for _, r in gb_sel.iterrows():
        mask = (
            (tmp_act["mce_target"] == r["mce_target"])
            & (tmp_act["bioref_organism"] == r["bioref_organism"])
            & (tmp_act["bioref_measurement_type"] == r["bioref_measurement_type"])
            & (tmp_act["bioref_std_measurement_unit"] == r["bioref_std_measurement_unit"])
            & (
                tmp_act["bioref_gene_name"].fillna("")
                == (r["bioref_gene_name"] if pd.notna(r["bioref_gene_name"]) else "")
            )
        )
        srcs = _collect_sources(tmp_act.loc[mask], r["bioref_measurement_type"])

        entry = {
            "gene": r["bioref_gene_name"] if pd.notna(r["bioref_gene_name"]) else None,
            "organism": r["bioref_organism"],
            "type": r["bioref_measurement_type"],
            "unit": r["bioref_std_measurement_unit"],
            "sources": srcs,
        }
        if int(r["count"]) == 1:
            entry["value"] = float(r["min"])
        else:
            entry["min"] = float(r["min"])
            entry["median"] = float(r["median"])
            entry["max"] = float(r["max"])
        aggregates.append(entry)

    return json.dumps(
        {
            "smiles": row["smiles"],
            "inchi_key": row["inchi_key"],
            "bioactivities": {"info": info, "aggregates": aggregates},
        },
        separators=(",", ":"),
    )

In [199]:
final_df_picked["bioactivities"] = final_df_picked.apply(build_pertubation_bioactivities, axis=1)

In [200]:
final_df_picked.to_parquet(
    "/Users/emmanuel.noutahi/Code/hooke-explain/data/curation_v1/perturbations/molecules_selected.parquet"
)

In [4]:
final_df_picked = pd.read_parquet(
    "/Users/emmanuel.noutahi/Code/hooke-explain/data/curation_v1/perturbations/molecules_selected.parquet"
)
final_df_picked.head()

,smiles,synonym_list,inchi_key,top_name_1,top_name_2,top_name_3,reason_1,reason_2,reason_3,bioactivities
0,BrC1=C(Br)C(Br)=C2C(=C1Br)N=NN2,"[4,5,6,7-tetrabromobenzotriazole, TBB benzotri...",OMZYUVOATZSGJY-UHFFFAOYSA-N,"4,5,6,7-tetrabromobenzotriazole",TBB,Casein Kinase II Inhibitor I,"4,5,6,7-tetrabromobenzotriazole is a well-know...",TBB is a common abbreviation used in scientifi...,Casein Kinase II Inhibitor I is a recognized n...,"{""synonym_names"":[""4,5,6,7-tetrabromobenzotria..."
1,BrC1=C(C2=NN=C(SCC(=O)NC(C3=CC=CS3)C3=CC=CC=C3...,"[AKOS001119592, Z97151845]",BJPSWVDDULSZMD-UHFFFAOYSA-N,None,None,None,None,None,None,"{""synonym_names"":[""AKOS001119592"",""Z97151845""]..."
2,BrC1=C(CN2C(=O)NC(C2=O)(C2=CC=CC=C2)C2=CC=CC=C...,"[AKOS007932363, Z14471460]",QEUFPVZFLQCQNK-UHFFFAOYSA-N,None,None,None,None,None,None,"{""synonym_names"":[""AKOS007932363"",""Z14471460""]..."
3,BrC1=C(C[N+]2(CCOCCC3[C@H]4C(C)(C)[C@H](C4)CC3...,"[SCHEMBL9359902, CHEMBL4303628, NCGC00388506-0...",DDHUTBKXLWCZCO-GFUWAVFVSA-N,None,None,None,None,None,None,"{""synonym_names"":[""NCGC00388506-02"",""SCHEMBL93..."
4,BrC1=C(F)C(Br)=CC2=C1CCC(C)N2C=O,"[6-Fluoro-5,7-dibromo-2-methyl-1-formyl-1,2,3,...",ZZLQPWXVZCPUGC-UHFFFAOYSA-N,"6-Fluoro-5,7-dibromo-2-methyl-1-formyl-1,2,3,4...",CE3F4,"5,7-Dibromo-6-fluoro-2-methyl-3,4-dihydroquino...","6-Fluoro-5,7-dibromo-2-methyl-1-formyl-1,2,3,4...",CE3F4 is a common research compound code.,"5,7-Dibromo-6-fluoro-2-methyl-3,4-dihydroquino...","{""synonym_names"":[""5,7-Dibromo-6-fluoro-2-meth..."

In [19]:
config = LLMConfig(
    provider="gemini",
    model="gemini-2.5-flash",
)

client = LLMClient(config)

2025-08-12 22:07:29.156 | INFO     | explain.llm._client:__init__:297 - Initialized Google Gemini client with model gemini-2.5-flash
2025-08-12 22:07:29.156 | INFO     | explain.llm._client:__init__:699 - Initialized unified LLM client with provider: gemini

In [20]:
client.generate([{"role": "user", "content": "Hello, how are you?"}])

LLMResponse(content="Hello! I'm doing well, thank you for asking.\n\nAs an AI, I don't have feelings or personal experiences, but I'm ready and able to assist you.\n\nHow are you doing today?", tool_calls=None, messages=[{'role': 'user', 'content': 'Hello, how are you?'}, {'role': 'assistant', 'content': "Hello! I'm doing well, thank you for asking.\n\nAs an AI, I don't have feelings or personal experiences, but I'm ready and able to assist you.\n\nHow are you doing today?"}])

In [ ]:
# Cell 4: Fast processing functions without type hints
def create_bioactivity_prompt(bioactivity_json, template):
    """Create a prompt for bioactivity summarization using the template."""
    return template.replace("{bioactivity_json}", bioactivity_json)


async def generate_bioactivity_summary(client, bioactivity_data, template, semaphore):
    """Generate a bioactivity summary for a single molecule."""
    async with semaphore:
        try:
            prompt = create_bioactivity_prompt(bioactivity_data, template)
            messages = [{"role": "user", "content": prompt}]
            response = await client.agenerate(messages)
            return response.content.strip()
        except Exception as e:
            print(f"Error generating summary: {e}")
            return f"Error generating summary: {str(e)}"


async def process_molecules_batch(client, molecules_batch, template, semaphore, batch_id, checkpoint_dir, pbar=None):
    """Process a batch of molecules and generate summaries with real-time progress."""
    batch_file = checkpoint_dir / f"summary_batch_{batch_id:04d}.json"

    # Check if this batch was already processed
    if batch_file.exists():
        if pbar:
            pbar.update(len(molecules_batch))
        return []  # Return empty since we're not reloading existing results

    try:
        batch_results = []

        for _idx, row in molecules_batch.iterrows():
            # Generate summary for this molecule's bioactivity data
            summary = await generate_bioactivity_summary(client, row["bioactivities"], template, semaphore)

            # Extract synonym names directly without parsing JSON again
            result = {
                "smiles": row["smiles"],
                "inchi_key": row.get("inchi_key"),
                "bioactivity_summary": summary,
                "original_bioactivities": row["bioactivities"],
            }
            batch_results.append(result)

            # Update progress bar immediately after each molecule
            if pbar:
                pbar.update(1)

        # Save batch result immediately
        with open(batch_file, "w") as f:
            json.dump(batch_results, f, indent=2)

        return batch_results

    except Exception as e:
        print(f"Batch {batch_id} processing failed: {e}")
        if pbar:
            pbar.update(len(molecules_batch))
        return []


def create_batches(df, batch_size=5):
    """Create batches of molecules for processing."""
    batches = []
    for i in range(0, len(df), batch_size):
        batches.append(df.iloc[i : i + batch_size])
    return batches


def count_existing_results(checkpoint_dir):
    """Fast count of existing results without loading all JSON."""
    if not checkpoint_dir.exists():
        return 0

    batch_files = list(checkpoint_dir.glob("summary_batch_*.json"))
    return len(batch_files)


async def process_bioactivity_summaries(
    client,
    df,
    template,
    batch_size=3,
    max_batches=None,
    max_concurrent=3,
    checkpoint_dir="../../data/curation_v1/perturbations/bioactivity_summaries",
):
    """Process molecules with real-time progress updates"""

    checkpoint_path = Path(checkpoint_dir)
    checkpoint_path.mkdir(parents=True, exist_ok=True)

    # Fast check for existing results
    existing_batch_count = count_existing_results(checkpoint_path)
    if existing_batch_count > 0:
        print(f"Found {existing_batch_count} existing batch files")

    # Create all batches upfront
    all_batches = create_batches(df, batch_size)
    if max_batches:
        all_batches = all_batches[:max_batches]

    # Skip already processed batches
    remaining_batches = all_batches[existing_batch_count:]

    if len(remaining_batches) == 0:
        print("All batches already processed!")
        return pd.DataFrame()  # Return empty for now, can load results later if needed

    total_molecules = sum(len(batch) for batch in remaining_batches)
    print(f"Processing {len(remaining_batches)} new batches ({total_molecules} molecules)")

    # Process batches one by one for real-time updates
    semaphore = asyncio.Semaphore(max_concurrent)
    all_results = []

    semaphore = asyncio.Semaphore(max_concurrent)

    # Create all tasks at once
    tasks = [
        process_molecules_batch(client, batch, template, semaphore, existing_batch_count + i, checkpoint_path)
        for i, batch in enumerate(remaining_batches)
    ]

    # Run all tasks concurrently with progress tracking
    all_results = []
    batch_results = await tqdm.gather(*tasks, desc="Processing batches")
    for results in batch_results:
        all_results.extend(results)

    print(f"\nProcessed {len(remaining_batches)} new batches")
    print(f"New results: {len(all_results)} molecules")

    return pd.DataFrame(all_results)


def load_all_results_when_needed(base_glob="../../data/curation_v1/perturbations/bioactivity_summaries*/"):
    """Load all results from multiple subdirectories only when explicitly requested."""
    all_results = []
    subdirs = sorted(Path().glob(base_glob))

    for subdir in subdirs:
        batch_files = sorted(subdir.glob("summary_batch_*.json"))
        print(f"Loading {len(batch_files)} batch files from {subdir}...")
        for batch_file in tqdm(batch_files, desc=f"Loading batches from {subdir}"):
            try:
                with open(batch_file) as f:
                    batch_results = json.load(f)
                    all_results.extend(batch_results)
            except Exception as e:
                print(f"Error loading {batch_file}: {e}")

    return pd.DataFrame(all_results)

In [ ]:
from tqdm.auto import tqdm

# Run the processing (start with a small test batch)
template = Path("../../data/curation_v1/templates/bioassay-to-report.txt").read_text()
for i in tqdm(range(0, 10), desc="Processing batches"):
    if i < 2:
        continue
    results_df = await process_bioactivity_summaries(
        client=client,
        df=final_df_picked.iloc[i * 1000 : (i + 1) * 1000],
        template=template,
        batch_size=5,
        max_batches=None,
        max_concurrent=30,
        checkpoint_dir=f"../../data/curation_v1/perturbations/bioactivity_summaries_{i + 1}",
    )

Processing batches:   0%|          | 0/10 [00:00<?, ?it/s]

Found 200 existing batch files
All batches already processed!
Processing 200 new batches (1000 molecules)

Processing batches: 100%|██████████| 200/200 [03:01<00:00,  1.10it/s]
Processing batches:  40%|████      | 4/10 [03:01<04:32, 45.44s/it]

Processed 200 new batches
New results: 1000 molecules
Processing 200 new batches (1000 molecules)

2025-08-12 22:28:06.626 | ERROR    | explain.llm._client:agenerate:448 - Gemini async generation failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}

Error generating summary: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}

Processing batches: 100%|██████████| 200/200 [03:17<00:00,  1.01it/s]
Processing batches:  50%|█████     | 5/10 [06:19<07:07, 85.44s/it]

Processed 200 new batches
New results: 1000 molecules
Processing 200 new batches (1000 molecules)

Processing batches: 100%|██████████| 200/200 [03:19<00:00,  1.00it/s]
Processing batches:  60%|██████    | 6/10 [09:38<07:46, 116.53s/it]

Processed 200 new batches
New results: 1000 molecules
Processing 200 new batches (1000 molecules)

Processing batches: 100%|██████████| 200/200 [03:16<00:00,  1.02it/s]
Processing batches:  70%|███████   | 7/10 [12:54<06:56, 139.00s/it]

Processed 200 new batches
New results: 1000 molecules
Processing 200 new batches (1000 molecules)

Processing batches: 100%|██████████| 200/200 [02:59<00:00,  1.12it/s]
Processing batches:  80%|████████  | 8/10 [15:54<05:00, 150.47s/it]

Processed 200 new batches
New results: 1000 molecules
Processing 200 new batches (1000 molecules)

Processing batches: 100%|██████████| 200/200 [03:09<00:00,  1.06it/s]
Processing batches:  90%|█████████ | 9/10 [19:03<02:41, 161.69s/it]

Processed 200 new batches
New results: 1000 molecules
Processing 94 new batches (466 molecules)

Processing batches: 100%|██████████| 94/94 [01:30<00:00,  1.04it/s]
Processing batches: 100%|██████████| 10/10 [20:33<00:00, 123.36s/it]

Processed 94 new batches
New results: 466 molecules

In [31]:
processed_bioactivity_summaries = load_all_results_when_needed()

Loading 200 batch files from bioactivity_summaries_1...

Loading batches from bioactivity_summaries_1: 100%|██████████| 200/200 [00:00<00:00, 7852.66it/s]

Loading 94 batch files from bioactivity_summaries_10...

Loading batches from bioactivity_summaries_10: 100%|██████████| 94/94 [00:00<00:00, 8398.08it/s]

Loading 200 batch files from bioactivity_summaries_2...

Loading batches from bioactivity_summaries_2: 100%|██████████| 200/200 [00:00<00:00, 8870.26it/s]

Loading 200 batch files from bioactivity_summaries_3...

Loading batches from bioactivity_summaries_3: 100%|██████████| 200/200 [00:00<00:00, 9786.74it/s]

Loading 200 batch files from bioactivity_summaries_4...

Loading batches from bioactivity_summaries_4: 100%|██████████| 200/200 [00:00<00:00, 10948.18it/s]

Loading 200 batch files from bioactivity_summaries_5...

Loading batches from bioactivity_summaries_5: 100%|██████████| 200/200 [00:00<00:00, 11459.22it/s]

Loading 200 batch files from bioactivity_summaries_6...

Loading batches from bioactivity_summaries_6: 100%|██████████| 200/200 [00:00<00:00, 12421.49it/s]

Loading 200 batch files from bioactivity_summaries_7...

Loading batches from bioactivity_summaries_7: 100%|██████████| 200/200 [00:00<00:00, 12020.65it/s]

Loading 200 batch files from bioactivity_summaries_8...

Loading batches from bioactivity_summaries_8: 100%|██████████| 200/200 [00:00<00:00, 12011.35it/s]

Loading 200 batch files from bioactivity_summaries_9...

Loading batches from bioactivity_summaries_9: 100%|██████████| 200/200 [00:00<00:00, 11208.27it/s]

In [37]:
final_df_picked.merge(
    processed_bioactivity_summaries.drop(columns=["original_bioactivities", "synonym_names"]),
    on=["smiles", "inchi_key"],
    how="inner",
).to_parquet("/Users/emmanuel.noutahi/Code/hooke-explain/data/curation_v1/perturbations/annotated_molecules.parquet")